// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xaxi_write_prova.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XAxi_write_prova_CfgInitialize(XAxi_write_prova *InstancePtr, XAxi_write_prova_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XAxi_write_prova_Start(XAxi_write_prova *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAxi_write_prova_ReadReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_AP_CTRL) & 0x80;
    XAxi_write_prova_WriteReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XAxi_write_prova_IsDone(XAxi_write_prova *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAxi_write_prova_ReadReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XAxi_write_prova_IsIdle(XAxi_write_prova *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAxi_write_prova_ReadReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XAxi_write_prova_IsReady(XAxi_write_prova *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAxi_write_prova_ReadReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XAxi_write_prova_EnableAutoRestart(XAxi_write_prova *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAxi_write_prova_WriteReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XAxi_write_prova_DisableAutoRestart(XAxi_write_prova *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAxi_write_prova_WriteReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_AP_CTRL, 0);
}

void XAxi_write_prova_Set_frame_index_V(XAxi_write_prova *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAxi_write_prova_WriteReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_FRAME_INDEX_V_DATA, Data);
}

u32 XAxi_write_prova_Get_frame_index_V(XAxi_write_prova *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAxi_write_prova_ReadReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_FRAME_INDEX_V_DATA);
    return Data;
}

void XAxi_write_prova_Set_base_address(XAxi_write_prova *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAxi_write_prova_WriteReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_BASE_ADDRESS_DATA, Data);
}

u32 XAxi_write_prova_Get_base_address(XAxi_write_prova *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAxi_write_prova_ReadReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_BASE_ADDRESS_DATA);
    return Data;
}

void XAxi_write_prova_Set_frame_buffer_dim(XAxi_write_prova *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAxi_write_prova_WriteReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_FRAME_BUFFER_DIM_DATA, Data);
}

u32 XAxi_write_prova_Get_frame_buffer_dim(XAxi_write_prova *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAxi_write_prova_ReadReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_FRAME_BUFFER_DIM_DATA);
    return Data;
}

void XAxi_write_prova_Set_frame_buffer_offset(XAxi_write_prova *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAxi_write_prova_WriteReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_FRAME_BUFFER_OFFSET_DATA, Data);
}

u32 XAxi_write_prova_Get_frame_buffer_offset(XAxi_write_prova *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAxi_write_prova_ReadReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_FRAME_BUFFER_OFFSET_DATA);
    return Data;
}

void XAxi_write_prova_Set_frame_buffer_number(XAxi_write_prova *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAxi_write_prova_WriteReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_FRAME_BUFFER_NUMBER_DATA, Data);
}

u32 XAxi_write_prova_Get_frame_buffer_number(XAxi_write_prova *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAxi_write_prova_ReadReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_FRAME_BUFFER_NUMBER_DATA);
    return Data;
}

void XAxi_write_prova_Set_update_intr(XAxi_write_prova *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAxi_write_prova_WriteReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_UPDATE_INTR_DATA, Data);
}

u32 XAxi_write_prova_Get_update_intr(XAxi_write_prova *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAxi_write_prova_ReadReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_UPDATE_INTR_DATA);
    return Data;
}

void XAxi_write_prova_InterruptGlobalEnable(XAxi_write_prova *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAxi_write_prova_WriteReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_GIE, 1);
}

void XAxi_write_prova_InterruptGlobalDisable(XAxi_write_prova *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAxi_write_prova_WriteReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_GIE, 0);
}

void XAxi_write_prova_InterruptEnable(XAxi_write_prova *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAxi_write_prova_ReadReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_IER);
    XAxi_write_prova_WriteReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_IER, Register | Mask);
}

void XAxi_write_prova_InterruptDisable(XAxi_write_prova *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAxi_write_prova_ReadReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_IER);
    XAxi_write_prova_WriteReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_IER, Register & (~Mask));
}

void XAxi_write_prova_InterruptClear(XAxi_write_prova *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAxi_write_prova_WriteReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_ISR, Mask);
}

u32 XAxi_write_prova_InterruptGetEnabled(XAxi_write_prova *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAxi_write_prova_ReadReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_IER);
}

u32 XAxi_write_prova_InterruptGetStatus(XAxi_write_prova *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAxi_write_prova_ReadReg(InstancePtr->Axilites_BaseAddress, XAXI_WRITE_PROVA_AXILITES_ADDR_ISR);
}

