// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XAXI_WRITE_PROVA_H
#define XAXI_WRITE_PROVA_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xaxi_write_prova_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XAxi_write_prova_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XAxi_write_prova;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XAxi_write_prova_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XAxi_write_prova_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XAxi_write_prova_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XAxi_write_prova_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XAxi_write_prova_Initialize(XAxi_write_prova *InstancePtr, u16 DeviceId);
XAxi_write_prova_Config* XAxi_write_prova_LookupConfig(u16 DeviceId);
int XAxi_write_prova_CfgInitialize(XAxi_write_prova *InstancePtr, XAxi_write_prova_Config *ConfigPtr);
#else
int XAxi_write_prova_Initialize(XAxi_write_prova *InstancePtr, const char* InstanceName);
int XAxi_write_prova_Release(XAxi_write_prova *InstancePtr);
#endif

void XAxi_write_prova_Start(XAxi_write_prova *InstancePtr);
u32 XAxi_write_prova_IsDone(XAxi_write_prova *InstancePtr);
u32 XAxi_write_prova_IsIdle(XAxi_write_prova *InstancePtr);
u32 XAxi_write_prova_IsReady(XAxi_write_prova *InstancePtr);
void XAxi_write_prova_EnableAutoRestart(XAxi_write_prova *InstancePtr);
void XAxi_write_prova_DisableAutoRestart(XAxi_write_prova *InstancePtr);

void XAxi_write_prova_Set_base_address(XAxi_write_prova *InstancePtr, u32 Data);
u32 XAxi_write_prova_Get_base_address(XAxi_write_prova *InstancePtr);
void XAxi_write_prova_Set_frame_buffer_dim(XAxi_write_prova *InstancePtr, u32 Data);
u32 XAxi_write_prova_Get_frame_buffer_dim(XAxi_write_prova *InstancePtr);
void XAxi_write_prova_Set_frame_buffer_offset(XAxi_write_prova *InstancePtr, u32 Data);
u32 XAxi_write_prova_Get_frame_buffer_offset(XAxi_write_prova *InstancePtr);
void XAxi_write_prova_Set_frame_buffer_number(XAxi_write_prova *InstancePtr, u32 Data);
u32 XAxi_write_prova_Get_frame_buffer_number(XAxi_write_prova *InstancePtr);
void XAxi_write_prova_Set_update_intr(XAxi_write_prova *InstancePtr, u32 Data);
u32 XAxi_write_prova_Get_update_intr(XAxi_write_prova *InstancePtr);

void XAxi_write_prova_InterruptGlobalEnable(XAxi_write_prova *InstancePtr);
void XAxi_write_prova_InterruptGlobalDisable(XAxi_write_prova *InstancePtr);
void XAxi_write_prova_InterruptEnable(XAxi_write_prova *InstancePtr, u32 Mask);
void XAxi_write_prova_InterruptDisable(XAxi_write_prova *InstancePtr, u32 Mask);
void XAxi_write_prova_InterruptClear(XAxi_write_prova *InstancePtr, u32 Mask);
u32 XAxi_write_prova_InterruptGetEnabled(XAxi_write_prova *InstancePtr);
u32 XAxi_write_prova_InterruptGetStatus(XAxi_write_prova *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
