
set_property IOSTANDARD LVCMOS18 [get_ports {LED_FRAME_VALID[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {href_V[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in_V[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in_V[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in_V[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in_V[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in_V[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in_V[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in_V[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in_V[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {vsync_V[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports reset_sw]
set_property IOSTANDARD LVCMOS18 [get_ports {OV7670_RESET[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports PCLK]
set_property IOSTANDARD LVCMOS18 [get_ports XCLK]
set_property PACKAGE_PIN A6 [get_ports {OV7670_RESET[0]}]
set_property PACKAGE_PIN D8 [get_ports reset_sw]
set_property PACKAGE_PIN E8 [get_ports {vsync_V[0]}]
set_property PACKAGE_PIN B7 [get_ports {LED_FRAME_VALID[0]}]
set_property PACKAGE_PIN C5 [get_ports {href_V[0]}]


set_property PACKAGE_PIN D5 [get_ports {data_in_V[7]}]
set_property PACKAGE_PIN C7 [get_ports {data_in_V[6]}]
set_property PACKAGE_PIN C8 [get_ports {data_in_V[5]}]
set_property PACKAGE_PIN A9 [get_ports {data_in_V[4]}]
set_property PACKAGE_PIN B9 [get_ports {data_in_V[3]}]
set_property PACKAGE_PIN A7 [get_ports {data_in_V[2]}]
set_property PACKAGE_PIN A8 [get_ports {data_in_V[1]}]
set_property PACKAGE_PIN B5 [get_ports {data_in_V[0]}]
set_property PACKAGE_PIN B6 [get_ports XCLK]
set_property PACKAGE_PIN A4 [get_ports PCLK]
