# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xczu3eg-sbva484-1-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.cache/wt [current_project]
set_property parent.project_path /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:ultra96:part0:1.0 [current_project]
set_property ip_repo_paths {
  /media/kidre/Dati/GIT_TEST/bare-metalProva/SmartCamera
  /media/kidre/Dati/GIT_TEST/bare-metalProva/IP_HLS_PROVA/axi_prova
  /home/kidre/Video/filtro_0
  /media/kidre/Dati/GIT_TEST/bare-metalProva/IP_HLS_PROVA/lettura_diretta
  /media/kidre/Dati/GIT_TEST/bare-metalProva/IP_HLS_PROVA/lettura_memcpy
} [current_project]
set_property ip_output_repo /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/hdl/prova_gr_wrapper.v
add_files /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/prova_gr.bd
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_axi_gpio_frame_intr_0/prova_gr_axi_gpio_frame_intr_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_axi_gpio_frame_intr_0/prova_gr_axi_gpio_frame_intr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_axi_gpio_frame_intr_0/prova_gr_axi_gpio_frame_intr_0.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_axi_gpio_pl_reset_0/prova_gr_axi_gpio_pl_reset_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_axi_gpio_pl_reset_0/prova_gr_axi_gpio_pl_reset_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_axi_gpio_pl_reset_0/prova_gr_axi_gpio_pl_reset_0.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_clk_wiz_0_0/prova_gr_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_clk_wiz_0_0/prova_gr_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_clk_wiz_0_0/prova_gr_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_proc_sys_reset_0_0/prova_gr_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_proc_sys_reset_0_0/prova_gr_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_proc_sys_reset_0_0/prova_gr_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_reset_100M_0/prova_gr_reset_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_reset_100M_0/prova_gr_reset_100M_0.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_reset_100M_0/prova_gr_reset_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_reset_24M_0/prova_gr_reset_24M_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_reset_24M_0/prova_gr_reset_24M_0.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_reset_24M_0/prova_gr_reset_24M_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_system_ila_0_0/bd_0/ip/ip_0/bd_65a8_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_system_ila_0_0/bd_0/bd_65a8_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_system_ila_0_0/prova_gr_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_zynq_ultra_ps_e_0_0/prova_gr_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_zynq_ultra_ps_e_0_0/prova_gr_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_c_counter_binary_0_0/prova_gr_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_ov7670_interface_0_0/constraints/ov7670_interface_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_LF_valid_to_AXIS_0/constraints/LF_valid_to_AXIS_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_ov7670_grayscale_0_0/constraints/ov7670_grayscale_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_xbar_1/prova_gr_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_axis_data_fifo_pipeline_to_writer_0/prova_gr_axis_data_fifo_pipeline_to_writer_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_axis_data_fifo_pipeline_to_writer_0/prova_gr_axis_data_fifo_pipeline_to_writer_0/prova_gr_axis_data_fifo_pipeline_to_writer_0.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_axis_data_fifo_pipeline_to_writer_0/prova_gr_axis_data_fifo_pipeline_to_writer_0/prova_gr_axis_data_fifo_pipeline_to_writer_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_axis_to_ddr_writer_0_0/constraints/axis_to_ddr_writer_ooc.xdc]
set_property used_in_synthesis false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_auto_ds_2/prova_gr_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_auto_ds_2/prova_gr_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_auto_ds_2/prova_gr_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_auto_pc_2/prova_gr_auto_pc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_auto_ds_1/prova_gr_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_auto_ds_1/prova_gr_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_auto_ds_1/prova_gr_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_auto_pc_1/prova_gr_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_auto_ds_0/prova_gr_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_auto_ds_0/prova_gr_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_auto_ds_0/prova_gr_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/ip/prova_gr_auto_pc_0/prova_gr_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/prova_gr/prova_gr_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/constrs_1/new/design_1_wrapper.xdc
set_property used_in_implementation false [get_files /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/constrs_1/new/design_1_wrapper.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top prova_gr_wrapper -part xczu3eg-sbva484-1-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef prova_gr_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file prova_gr_wrapper_utilization_synth.rpt -pb prova_gr_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
