# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/reset_3/ip/reset_3_xbar_2/reset_3_xbar_2.xci
# IP: The module: 'reset_3_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/reset_3/ip/reset_3_xbar_2/reset_3_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'reset_3_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/reset_3/ip/reset_3_xbar_2/reset_3_xbar_2.xci
# IP: The module: 'reset_3_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/reset_3/ip/reset_3_xbar_2/reset_3_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'reset_3_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
