// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XOV7670_BUFFER_H
#define XOV7670_BUFFER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xov7670_buffer_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XOv7670_buffer_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XOv7670_buffer;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XOv7670_buffer_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XOv7670_buffer_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XOv7670_buffer_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XOv7670_buffer_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XOv7670_buffer_Initialize(XOv7670_buffer *InstancePtr, u16 DeviceId);
XOv7670_buffer_Config* XOv7670_buffer_LookupConfig(u16 DeviceId);
int XOv7670_buffer_CfgInitialize(XOv7670_buffer *InstancePtr, XOv7670_buffer_Config *ConfigPtr);
#else
int XOv7670_buffer_Initialize(XOv7670_buffer *InstancePtr, const char* InstanceName);
int XOv7670_buffer_Release(XOv7670_buffer *InstancePtr);
#endif


void XOv7670_buffer_Set_outStream_grayscale_V(XOv7670_buffer *InstancePtr, u32 Data);
u32 XOv7670_buffer_Get_outStream_grayscale_V(XOv7670_buffer *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
