// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "ddr_to_axis_reader.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic ddr_to_axis_reader::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic ddr_to_axis_reader::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<13> ddr_to_axis_reader::ap_ST_fsm_state1 = "1";
const sc_lv<13> ddr_to_axis_reader::ap_ST_fsm_state2 = "10";
const sc_lv<13> ddr_to_axis_reader::ap_ST_fsm_state3 = "100";
const sc_lv<13> ddr_to_axis_reader::ap_ST_fsm_state4 = "1000";
const sc_lv<13> ddr_to_axis_reader::ap_ST_fsm_state5 = "10000";
const sc_lv<13> ddr_to_axis_reader::ap_ST_fsm_state6 = "100000";
const sc_lv<13> ddr_to_axis_reader::ap_ST_fsm_state7 = "1000000";
const sc_lv<13> ddr_to_axis_reader::ap_ST_fsm_state8 = "10000000";
const sc_lv<13> ddr_to_axis_reader::ap_ST_fsm_state9 = "100000000";
const sc_lv<13> ddr_to_axis_reader::ap_ST_fsm_pp0_stage0 = "1000000000";
const sc_lv<13> ddr_to_axis_reader::ap_ST_fsm_state13 = "10000000000";
const sc_lv<13> ddr_to_axis_reader::ap_ST_fsm_pp1_stage0 = "100000000000";
const sc_lv<13> ddr_to_axis_reader::ap_ST_fsm_state17 = "1000000000000";
const sc_lv<32> ddr_to_axis_reader::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool ddr_to_axis_reader::ap_const_boolean_1 = true;
const sc_lv<1> ddr_to_axis_reader::ap_const_lv1_0 = "0";
const sc_lv<1> ddr_to_axis_reader::ap_const_lv1_1 = "1";
const sc_lv<2> ddr_to_axis_reader::ap_const_lv2_0 = "00";
const sc_lv<2> ddr_to_axis_reader::ap_const_lv2_2 = "10";
const sc_lv<2> ddr_to_axis_reader::ap_const_lv2_3 = "11";
const sc_lv<2> ddr_to_axis_reader::ap_const_lv2_1 = "1";
const sc_lv<32> ddr_to_axis_reader::ap_const_lv32_8 = "1000";
const sc_lv<32> ddr_to_axis_reader::ap_const_lv32_B = "1011";
const bool ddr_to_axis_reader::ap_const_boolean_0 = false;
const sc_lv<32> ddr_to_axis_reader::ap_const_lv32_2 = "10";
const sc_lv<32> ddr_to_axis_reader::ap_const_lv32_9 = "1001";
const int ddr_to_axis_reader::C_S_AXI_DATA_WIDTH = "100000";
const int ddr_to_axis_reader::C_M_AXI_BASE_DDR_ADDR_TARGET_ADDR = "0000000000000000000000000000000000000000000000000000000000000000";
const int ddr_to_axis_reader::C_M_AXI_BASE_DDR_ADDR_USER_VALUE = "0000000000000000000000000000000000000000000000000000000000000000";
const int ddr_to_axis_reader::C_M_AXI_BASE_DDR_ADDR_PROT_VALUE = "0000000000000000000000000000000000000000000000000000000000000000";
const int ddr_to_axis_reader::C_M_AXI_BASE_DDR_ADDR_CACHE_VALUE = "11";
const int ddr_to_axis_reader::C_M_AXI_DATA_WIDTH = "100000";
const sc_lv<32> ddr_to_axis_reader::ap_const_lv32_1 = "1";
const sc_lv<32> ddr_to_axis_reader::ap_const_lv32_C = "1100";
const sc_lv<32> ddr_to_axis_reader::ap_const_lv32_A = "1010";
const sc_lv<10> ddr_to_axis_reader::ap_const_lv10_0 = "0000000000";
const sc_lv<13> ddr_to_axis_reader::ap_const_lv13_0 = "0000000000000";
const sc_lv<32> ddr_to_axis_reader::ap_const_lv32_200 = "1000000000";
const sc_lv<3> ddr_to_axis_reader::ap_const_lv3_0 = "000";
const sc_lv<4> ddr_to_axis_reader::ap_const_lv4_0 = "0000";
const sc_lv<32> ddr_to_axis_reader::ap_const_lv32_3 = "11";
const sc_lv<32> ddr_to_axis_reader::ap_const_lv32_1F = "11111";
const sc_lv<8> ddr_to_axis_reader::ap_const_lv8_0 = "00000000";
const sc_lv<8> ddr_to_axis_reader::ap_const_lv8_FF = "11111111";
const sc_lv<32> ddr_to_axis_reader::ap_const_lv32_22 = "100010";
const sc_lv<10> ddr_to_axis_reader::ap_const_lv10_200 = "1000000000";
const sc_lv<10> ddr_to_axis_reader::ap_const_lv10_1 = "1";
const sc_lv<13> ddr_to_axis_reader::ap_const_lv13_1000 = "1000000000000";
const sc_lv<13> ddr_to_axis_reader::ap_const_lv13_1 = "1";
const sc_lv<6> ddr_to_axis_reader::ap_const_lv6_7 = "111";
const sc_lv<32> ddr_to_axis_reader::ap_const_lv32_3F = "111111";
const sc_lv<7> ddr_to_axis_reader::ap_const_lv7_3F = "111111";
const sc_lv<64> ddr_to_axis_reader::ap_const_lv64_FFFFFFFFFFFFFFFF = "1111111111111111111111111111111111111111111111111111111111111111";
const sc_lv<64> ddr_to_axis_reader::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";

ddr_to_axis_reader::ddr_to_axis_reader(sc_module_name name) : sc_module(name), mVcdFile(0) {
    ddr_to_axis_reader_AXILiteS_s_axi_U = new ddr_to_axis_reader_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("ddr_to_axis_reader_AXILiteS_s_axi_U");
    ddr_to_axis_reader_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    ddr_to_axis_reader_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    ddr_to_axis_reader_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    ddr_to_axis_reader_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    ddr_to_axis_reader_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    ddr_to_axis_reader_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    ddr_to_axis_reader_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    ddr_to_axis_reader_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    ddr_to_axis_reader_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    ddr_to_axis_reader_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    ddr_to_axis_reader_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    ddr_to_axis_reader_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    ddr_to_axis_reader_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    ddr_to_axis_reader_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    ddr_to_axis_reader_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    ddr_to_axis_reader_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    ddr_to_axis_reader_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    ddr_to_axis_reader_AXILiteS_s_axi_U->ACLK(ap_clk);
    ddr_to_axis_reader_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    ddr_to_axis_reader_AXILiteS_s_axi_U->ACLK_EN(ap_var_for_const0);
    ddr_to_axis_reader_AXILiteS_s_axi_U->ap_start(ap_start);
    ddr_to_axis_reader_AXILiteS_s_axi_U->interrupt(interrupt);
    ddr_to_axis_reader_AXILiteS_s_axi_U->ap_ready(ap_ready);
    ddr_to_axis_reader_AXILiteS_s_axi_U->ap_done(ap_done);
    ddr_to_axis_reader_AXILiteS_s_axi_U->ap_idle(ap_idle);
    ddr_to_axis_reader_AXILiteS_s_axi_U->base_address(base_address);
    ddr_to_axis_reader_AXILiteS_s_axi_U->frame_buffer_dim(frame_buffer_dim);
    ddr_to_axis_reader_AXILiteS_s_axi_U->frame_buffer_offset(frame_buffer_offset);
    ddr_to_axis_reader_AXILiteS_s_axi_U->frame_buffer_number(frame_buffer_number);
    ddr_to_axis_reader_AXILiteS_s_axi_U->update_intr(update_intr);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U = new ddr_to_axis_reader_base_ddr_addr_m_axi<0,64,32,5,16,16,16,16,C_M_AXI_BASE_DDR_ADDR_ID_WIDTH,C_M_AXI_BASE_DDR_ADDR_ADDR_WIDTH,C_M_AXI_BASE_DDR_ADDR_DATA_WIDTH,C_M_AXI_BASE_DDR_ADDR_AWUSER_WIDTH,C_M_AXI_BASE_DDR_ADDR_ARUSER_WIDTH,C_M_AXI_BASE_DDR_ADDR_WUSER_WIDTH,C_M_AXI_BASE_DDR_ADDR_RUSER_WIDTH,C_M_AXI_BASE_DDR_ADDR_BUSER_WIDTH,C_M_AXI_BASE_DDR_ADDR_TARGET_ADDR,C_M_AXI_BASE_DDR_ADDR_USER_VALUE,C_M_AXI_BASE_DDR_ADDR_PROT_VALUE,C_M_AXI_BASE_DDR_ADDR_CACHE_VALUE>("ddr_to_axis_reader_base_ddr_addr_m_axi_U");
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->AWVALID(m_axi_base_ddr_addr_AWVALID);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->AWREADY(m_axi_base_ddr_addr_AWREADY);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->AWADDR(m_axi_base_ddr_addr_AWADDR);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->AWID(m_axi_base_ddr_addr_AWID);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->AWLEN(m_axi_base_ddr_addr_AWLEN);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->AWSIZE(m_axi_base_ddr_addr_AWSIZE);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->AWBURST(m_axi_base_ddr_addr_AWBURST);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->AWLOCK(m_axi_base_ddr_addr_AWLOCK);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->AWCACHE(m_axi_base_ddr_addr_AWCACHE);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->AWPROT(m_axi_base_ddr_addr_AWPROT);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->AWQOS(m_axi_base_ddr_addr_AWQOS);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->AWREGION(m_axi_base_ddr_addr_AWREGION);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->AWUSER(m_axi_base_ddr_addr_AWUSER);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->WVALID(m_axi_base_ddr_addr_WVALID);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->WREADY(m_axi_base_ddr_addr_WREADY);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->WDATA(m_axi_base_ddr_addr_WDATA);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->WSTRB(m_axi_base_ddr_addr_WSTRB);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->WLAST(m_axi_base_ddr_addr_WLAST);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->WID(m_axi_base_ddr_addr_WID);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->WUSER(m_axi_base_ddr_addr_WUSER);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->ARVALID(m_axi_base_ddr_addr_ARVALID);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->ARREADY(m_axi_base_ddr_addr_ARREADY);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->ARADDR(m_axi_base_ddr_addr_ARADDR);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->ARID(m_axi_base_ddr_addr_ARID);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->ARLEN(m_axi_base_ddr_addr_ARLEN);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->ARSIZE(m_axi_base_ddr_addr_ARSIZE);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->ARBURST(m_axi_base_ddr_addr_ARBURST);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->ARLOCK(m_axi_base_ddr_addr_ARLOCK);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->ARCACHE(m_axi_base_ddr_addr_ARCACHE);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->ARPROT(m_axi_base_ddr_addr_ARPROT);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->ARQOS(m_axi_base_ddr_addr_ARQOS);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->ARREGION(m_axi_base_ddr_addr_ARREGION);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->ARUSER(m_axi_base_ddr_addr_ARUSER);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->RVALID(m_axi_base_ddr_addr_RVALID);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->RREADY(m_axi_base_ddr_addr_RREADY);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->RDATA(m_axi_base_ddr_addr_RDATA);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->RLAST(m_axi_base_ddr_addr_RLAST);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->RID(m_axi_base_ddr_addr_RID);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->RUSER(m_axi_base_ddr_addr_RUSER);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->RRESP(m_axi_base_ddr_addr_RRESP);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->BVALID(m_axi_base_ddr_addr_BVALID);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->BREADY(m_axi_base_ddr_addr_BREADY);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->BRESP(m_axi_base_ddr_addr_BRESP);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->BID(m_axi_base_ddr_addr_BID);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->BUSER(m_axi_base_ddr_addr_BUSER);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->ACLK(ap_clk);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->ARESET(ap_rst_n_inv);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->ACLK_EN(ap_var_for_const0);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_ARVALID(base_ddr_addr_ARVALID);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_ARREADY(base_ddr_addr_ARREADY);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_ARADDR(base_ddr_addr_ARADDR);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_ARID(ap_var_for_const1);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_ARLEN(ap_var_for_const2);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_ARSIZE(ap_var_for_const3);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_ARLOCK(ap_var_for_const4);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_ARCACHE(ap_var_for_const5);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_ARQOS(ap_var_for_const5);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_ARPROT(ap_var_for_const3);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_ARUSER(ap_var_for_const1);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_ARBURST(ap_var_for_const4);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_ARREGION(ap_var_for_const5);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_RVALID(base_ddr_addr_RVALID);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_RREADY(base_ddr_addr_RREADY);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_RDATA(base_ddr_addr_RDATA);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_RID(base_ddr_addr_RID);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_RUSER(base_ddr_addr_RUSER);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_RRESP(base_ddr_addr_RRESP);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_RLAST(base_ddr_addr_RLAST);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_AWVALID(ap_var_for_const6);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_AWREADY(base_ddr_addr_AWREADY);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_AWADDR(ap_var_for_const7);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_AWID(ap_var_for_const1);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_AWLEN(ap_var_for_const7);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_AWSIZE(ap_var_for_const3);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_AWLOCK(ap_var_for_const4);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_AWCACHE(ap_var_for_const5);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_AWQOS(ap_var_for_const5);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_AWPROT(ap_var_for_const3);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_AWUSER(ap_var_for_const1);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_AWBURST(ap_var_for_const4);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_AWREGION(ap_var_for_const5);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_WVALID(ap_var_for_const6);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_WREADY(base_ddr_addr_WREADY);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_WDATA(ap_var_for_const8);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_WID(ap_var_for_const1);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_WUSER(ap_var_for_const1);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_WLAST(ap_var_for_const6);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_WSTRB(ap_var_for_const9);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_BVALID(base_ddr_addr_BVALID);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_BREADY(ap_var_for_const6);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_BRESP(base_ddr_addr_BRESP);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_BID(base_ddr_addr_BID);
    ddr_to_axis_reader_base_ddr_addr_m_axi_U->I_BUSER(base_ddr_addr_BUSER);
    buffer_U = new ddr_to_axis_readebkb("buffer_U");
    buffer_U->clk(ap_clk);
    buffer_U->reset(ap_rst_n_inv);
    buffer_U->address0(buffer_address0);
    buffer_U->ce0(buffer_ce0);
    buffer_U->q0(buffer_q0);
    buffer_U->address1(buffer_address1);
    buffer_U->ce1(buffer_ce1);
    buffer_U->we1(buffer_we1);
    buffer_U->d1(base_ddr_addr_addr_r_reg_689);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_reg_680 );
    sensitive << ( base_ddr_addr_RVALID );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_reg_680 );
    sensitive << ( base_ddr_addr_RVALID );

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_01001);

    SC_METHOD(thread_ap_block_pp1_stage0_11001);
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_block_state15_io );
    sensitive << ( ap_block_state16_io );

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_block_state15_io );
    sensitive << ( ap_block_state16_io );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter1);
    sensitive << ( exitcond_reg_680 );
    sensitive << ( base_ddr_addr_RVALID );

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state14_pp1_stage0_iter0);

    SC_METHOD(thread_ap_block_state15_io);
    sensitive << ( outStream_V_1_ack_in );
    sensitive << ( tmp_9_reg_694 );

    SC_METHOD(thread_ap_block_state15_pp1_stage0_iter1);

    SC_METHOD(thread_ap_block_state16_io);
    sensitive << ( outStream_V_1_ack_in );
    sensitive << ( tmp_9_reg_694_pp1_iter1_reg );

    SC_METHOD(thread_ap_block_state16_pp1_stage0_iter2);

    SC_METHOD(thread_ap_block_state3_io);
    sensitive << ( tmp_7_fu_425_p2 );
    sensitive << ( ap_sig_ioackin_base_ddr_addr_ARREADY );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state10);
    sensitive << ( exitcond_fu_448_p2 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state14);
    sensitive << ( tmp_9_fu_465_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( outStream_V_1_ack_in );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_7_fu_425_p2 );
    sensitive << ( ap_block_state3_io );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_ap_phi_mux_indvar_phi_fu_282_p4);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond_reg_680 );
    sensitive << ( indvar_reg_278 );
    sensitive << ( indvar_next_reg_684 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( outStream_V_1_ack_in );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_7_fu_425_p2 );
    sensitive << ( ap_block_state3_io );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_ioackin_base_ddr_addr_ARREADY);
    sensitive << ( base_ddr_addr_ARREADY );
    sensitive << ( ap_reg_ioackin_base_ddr_addr_ARREADY );

    SC_METHOD(thread_base_ddr_addr_ARADDR);
    sensitive << ( outStream_V_1_ack_in );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_7_fu_425_p2 );
    sensitive << ( tmp_8_fu_437_p1 );
    sensitive << ( ap_reg_ioackin_base_ddr_addr_ARREADY );

    SC_METHOD(thread_base_ddr_addr_ARVALID);
    sensitive << ( outStream_V_1_ack_in );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_7_fu_425_p2 );
    sensitive << ( ap_reg_ioackin_base_ddr_addr_ARREADY );

    SC_METHOD(thread_base_ddr_addr_RREADY);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_reg_680 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_base_ddr_addr_blk_n_AR);
    sensitive << ( m_axi_base_ddr_addr_ARREADY );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_7_fu_425_p2 );

    SC_METHOD(thread_base_ddr_addr_blk_n_R);
    sensitive << ( m_axi_base_ddr_addr_RVALID );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond_reg_680 );

    SC_METHOD(thread_buffer_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( gepindex2_cast_fu_491_p1 );

    SC_METHOD(thread_buffer_address1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( indvar1_fu_460_p1 );

    SC_METHOD(thread_buffer_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_buffer_ce1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_buffer_we1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( exitcond_reg_680_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_end_pos_fu_503_p2);
    sensitive << ( start_pos_fu_496_p3 );

    SC_METHOD(thread_exitcond_fu_448_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_phi_fu_282_p4 );

    SC_METHOD(thread_gepindex2_cast_fu_491_p1);
    sensitive << ( gepindex_cast_fu_481_p4 );

    SC_METHOD(thread_gepindex_cast_fu_481_p4);
    sensitive << ( j_reg_290 );

    SC_METHOD(thread_i_1_fu_431_p2);
    sensitive << ( i_reg_267 );

    SC_METHOD(thread_indvar1_fu_460_p1);
    sensitive << ( indvar_reg_278_pp0_iter1_reg );

    SC_METHOD(thread_indvar_next_fu_454_p2);
    sensitive << ( ap_phi_mux_indvar_phi_fu_282_p4 );

    SC_METHOD(thread_inner_index_V_1_fu_371_p2);
    sensitive << ( t_V_fu_365_p3 );

    SC_METHOD(thread_j_1_fu_471_p2);
    sensitive << ( j_reg_290 );

    SC_METHOD(thread_offset_1_fu_612_p2);
    sensitive << ( offset1_reg_257 );

    SC_METHOD(thread_offset_fu_401_p2);
    sensitive << ( i_op_assign_1_reg_239 );
    sensitive << ( tmp_s_fu_391_p4 );

    SC_METHOD(thread_outStream_V_1_ack_in);
    sensitive << ( outStream_V_1_state );

    SC_METHOD(thread_outStream_V_1_ack_out);
    sensitive << ( outStream_V_TREADY );

    SC_METHOD(thread_outStream_V_1_data_out);
    sensitive << ( outStream_V_1_payload_A );
    sensitive << ( outStream_V_1_payload_B );
    sensitive << ( outStream_V_1_sel );

    SC_METHOD(thread_outStream_V_1_load_A);
    sensitive << ( outStream_V_1_sel_wr );
    sensitive << ( outStream_V_1_state_cmp_full );

    SC_METHOD(thread_outStream_V_1_load_B);
    sensitive << ( outStream_V_1_sel_wr );
    sensitive << ( outStream_V_1_state_cmp_full );

    SC_METHOD(thread_outStream_V_1_sel);
    sensitive << ( outStream_V_1_sel_rd );

    SC_METHOD(thread_outStream_V_1_state_cmp_full);
    sensitive << ( outStream_V_1_state );

    SC_METHOD(thread_outStream_V_1_vld_in);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( tmp_9_reg_694 );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_outStream_V_1_vld_out);
    sensitive << ( outStream_V_1_state );

    SC_METHOD(thread_outStream_V_TDATA);
    sensitive << ( outStream_V_1_data_out );

    SC_METHOD(thread_outStream_V_TDATA_blk_n);
    sensitive << ( outStream_V_1_state );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( tmp_9_reg_694 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( tmp_9_reg_694_pp1_iter1_reg );

    SC_METHOD(thread_outStream_V_TVALID);
    sensitive << ( outStream_V_1_state );

    SC_METHOD(thread_r_V_fu_385_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( r_V_fu_385_p00 );

    SC_METHOD(thread_r_V_fu_385_p00);
    sensitive << ( inner_index_V_1_fu_371_p2 );

    SC_METHOD(thread_r_V_fu_385_p1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( r_V_fu_385_p10 );

    SC_METHOD(thread_r_V_fu_385_p10);
    sensitive << ( i_op_assign_reg_230 );

    SC_METHOD(thread_r_V_fu_385_p2);
    sensitive << ( r_V_fu_385_p0 );
    sensitive << ( r_V_fu_385_p1 );

    SC_METHOD(thread_start_pos_fu_496_p3);
    sensitive << ( tmp_12_reg_703 );

    SC_METHOD(thread_t_V_fu_365_p3);
    sensitive << ( frame_index_V );
    sensitive << ( tmp_4_reg_656 );
    sensitive << ( tmp_fu_361_p1 );

    SC_METHOD(thread_tmp_10_fu_421_p1);
    sensitive << ( tmp_6_fu_411_p4 );

    SC_METHOD(thread_tmp_12_fu_477_p1);
    sensitive << ( j_reg_290 );

    SC_METHOD(thread_tmp_13_fu_509_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( tmp_9_reg_694 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( start_pos_fu_496_p3 );
    sensitive << ( end_pos_fu_503_p2 );

    SC_METHOD(thread_tmp_14_fu_515_p1);
    sensitive << ( start_pos_fu_496_p3 );

    SC_METHOD(thread_tmp_15_fu_519_p1);
    sensitive << ( end_pos_fu_503_p2 );

    SC_METHOD(thread_tmp_16_fu_523_p4);
    sensitive << ( buffer_q0 );

    SC_METHOD(thread_tmp_17_fu_533_p2);
    sensitive << ( tmp_14_fu_515_p1 );
    sensitive << ( tmp_15_fu_519_p1 );

    SC_METHOD(thread_tmp_18_fu_539_p2);
    sensitive << ( tmp_14_fu_515_p1 );

    SC_METHOD(thread_tmp_19_fu_545_p2);
    sensitive << ( tmp_14_fu_515_p1 );
    sensitive << ( tmp_15_fu_519_p1 );

    SC_METHOD(thread_tmp_1_fu_301_p1);
    sensitive << ( frame_buffer_number );

    SC_METHOD(thread_tmp_20_fu_551_p3);
    sensitive << ( tmp_13_fu_509_p2 );
    sensitive << ( tmp_17_fu_533_p2 );
    sensitive << ( tmp_19_fu_545_p2 );

    SC_METHOD(thread_tmp_21_fu_559_p3);
    sensitive << ( buffer_q0 );
    sensitive << ( tmp_13_fu_509_p2 );
    sensitive << ( tmp_16_fu_523_p4 );

    SC_METHOD(thread_tmp_22_fu_567_p3);
    sensitive << ( tmp_14_fu_515_p1 );
    sensitive << ( tmp_13_fu_509_p2 );
    sensitive << ( tmp_18_fu_539_p2 );

    SC_METHOD(thread_tmp_23_fu_575_p2);
    sensitive << ( tmp_20_fu_551_p3 );

    SC_METHOD(thread_tmp_24_fu_581_p1);
    sensitive << ( tmp_22_fu_567_p3 );

    SC_METHOD(thread_tmp_25_fu_585_p1);
    sensitive << ( tmp_23_fu_575_p2 );

    SC_METHOD(thread_tmp_26_fu_589_p2);
    sensitive << ( tmp_21_fu_559_p3 );
    sensitive << ( tmp_24_fu_581_p1 );

    SC_METHOD(thread_tmp_27_fu_595_p2);
    sensitive << ( tmp_25_fu_585_p1 );

    SC_METHOD(thread_tmp_28_fu_601_p2);
    sensitive << ( tmp_26_fu_589_p2 );
    sensitive << ( tmp_27_fu_595_p2 );

    SC_METHOD(thread_tmp_29_fu_607_p1);
    sensitive << ( tmp_28_fu_601_p2 );

    SC_METHOD(thread_tmp_2_fu_335_p4);
    sensitive << ( base_address );

    SC_METHOD(thread_tmp_4_fu_355_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( frame_index_V );

    SC_METHOD(thread_tmp_5_fu_345_p1);
    sensitive << ( tmp_2_fu_335_p4 );

    SC_METHOD(thread_tmp_6_fu_411_p4);
    sensitive << ( FRAME_BUFFER_DIM_r );

    SC_METHOD(thread_tmp_7_fu_425_p2);
    sensitive << ( outStream_V_1_ack_in );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_block_state3_io );
    sensitive << ( i_reg_267 );
    sensitive << ( tmp_10_fu_421_p1 );

    SC_METHOD(thread_tmp_8_fu_437_p1);
    sensitive << ( offset1_reg_257 );

    SC_METHOD(thread_tmp_9_fu_465_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( j_reg_290 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_tmp_fu_361_p1);
    sensitive << ( tmp_3_reg_248 );

    SC_METHOD(thread_tmp_s_fu_391_p4);
    sensitive << ( r_V_fu_385_p2 );

    SC_METHOD(thread_update_intr_read_read_fu_154_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( update_intr );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( outStream_V_1_ack_in );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_7_fu_425_p2 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_state3_io );
    sensitive << ( exitcond_fu_448_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_9_fu_465_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp1_stage0_subdone );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const6);

    SC_THREAD(thread_ap_var_for_const7);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const4);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const3);

    SC_THREAD(thread_ap_var_for_const5);

    SC_THREAD(thread_ap_var_for_const9);

    SC_THREAD(thread_ap_var_for_const8);

    ap_CS_fsm = "0000000000001";
    outStream_V_1_sel_rd = SC_LOGIC_0;
    outStream_V_1_sel_wr = SC_LOGIC_0;
    outStream_V_1_state = "00";
    FRAME_OFFSET = "00000000000001001011000000000000";
    FRAME_BUFFER_NUMBER_r = "00000000000000000000000000001000";
    BASE_ADDRESS_r = "00000000000000000000000000001000";
    FRAME_BUFFER_DIM_r = "00000000000001001011000000000000";
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_reg_ioackin_base_ddr_addr_ARREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "ddr_to_axis_reader_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, outStream_V_TDATA, "(port)outStream_V_TDATA");
    sc_trace(mVcdFile, outStream_V_TVALID, "(port)outStream_V_TVALID");
    sc_trace(mVcdFile, outStream_V_TREADY, "(port)outStream_V_TREADY");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_AWVALID, "(port)m_axi_base_ddr_addr_AWVALID");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_AWREADY, "(port)m_axi_base_ddr_addr_AWREADY");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_AWADDR, "(port)m_axi_base_ddr_addr_AWADDR");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_AWID, "(port)m_axi_base_ddr_addr_AWID");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_AWLEN, "(port)m_axi_base_ddr_addr_AWLEN");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_AWSIZE, "(port)m_axi_base_ddr_addr_AWSIZE");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_AWBURST, "(port)m_axi_base_ddr_addr_AWBURST");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_AWLOCK, "(port)m_axi_base_ddr_addr_AWLOCK");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_AWCACHE, "(port)m_axi_base_ddr_addr_AWCACHE");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_AWPROT, "(port)m_axi_base_ddr_addr_AWPROT");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_AWQOS, "(port)m_axi_base_ddr_addr_AWQOS");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_AWREGION, "(port)m_axi_base_ddr_addr_AWREGION");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_AWUSER, "(port)m_axi_base_ddr_addr_AWUSER");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_WVALID, "(port)m_axi_base_ddr_addr_WVALID");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_WREADY, "(port)m_axi_base_ddr_addr_WREADY");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_WDATA, "(port)m_axi_base_ddr_addr_WDATA");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_WSTRB, "(port)m_axi_base_ddr_addr_WSTRB");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_WLAST, "(port)m_axi_base_ddr_addr_WLAST");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_WID, "(port)m_axi_base_ddr_addr_WID");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_WUSER, "(port)m_axi_base_ddr_addr_WUSER");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_ARVALID, "(port)m_axi_base_ddr_addr_ARVALID");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_ARREADY, "(port)m_axi_base_ddr_addr_ARREADY");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_ARADDR, "(port)m_axi_base_ddr_addr_ARADDR");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_ARID, "(port)m_axi_base_ddr_addr_ARID");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_ARLEN, "(port)m_axi_base_ddr_addr_ARLEN");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_ARSIZE, "(port)m_axi_base_ddr_addr_ARSIZE");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_ARBURST, "(port)m_axi_base_ddr_addr_ARBURST");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_ARLOCK, "(port)m_axi_base_ddr_addr_ARLOCK");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_ARCACHE, "(port)m_axi_base_ddr_addr_ARCACHE");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_ARPROT, "(port)m_axi_base_ddr_addr_ARPROT");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_ARQOS, "(port)m_axi_base_ddr_addr_ARQOS");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_ARREGION, "(port)m_axi_base_ddr_addr_ARREGION");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_ARUSER, "(port)m_axi_base_ddr_addr_ARUSER");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_RVALID, "(port)m_axi_base_ddr_addr_RVALID");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_RREADY, "(port)m_axi_base_ddr_addr_RREADY");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_RDATA, "(port)m_axi_base_ddr_addr_RDATA");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_RLAST, "(port)m_axi_base_ddr_addr_RLAST");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_RID, "(port)m_axi_base_ddr_addr_RID");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_RUSER, "(port)m_axi_base_ddr_addr_RUSER");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_RRESP, "(port)m_axi_base_ddr_addr_RRESP");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_BVALID, "(port)m_axi_base_ddr_addr_BVALID");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_BREADY, "(port)m_axi_base_ddr_addr_BREADY");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_BRESP, "(port)m_axi_base_ddr_addr_BRESP");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_BID, "(port)m_axi_base_ddr_addr_BID");
    sc_trace(mVcdFile, m_axi_base_ddr_addr_BUSER, "(port)m_axi_base_ddr_addr_BUSER");
    sc_trace(mVcdFile, frame_index_V, "(port)frame_index_V");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, outStream_V_1_data_out, "outStream_V_1_data_out");
    sc_trace(mVcdFile, outStream_V_1_vld_in, "outStream_V_1_vld_in");
    sc_trace(mVcdFile, outStream_V_1_vld_out, "outStream_V_1_vld_out");
    sc_trace(mVcdFile, outStream_V_1_ack_in, "outStream_V_1_ack_in");
    sc_trace(mVcdFile, outStream_V_1_ack_out, "outStream_V_1_ack_out");
    sc_trace(mVcdFile, outStream_V_1_payload_A, "outStream_V_1_payload_A");
    sc_trace(mVcdFile, outStream_V_1_payload_B, "outStream_V_1_payload_B");
    sc_trace(mVcdFile, outStream_V_1_sel_rd, "outStream_V_1_sel_rd");
    sc_trace(mVcdFile, outStream_V_1_sel_wr, "outStream_V_1_sel_wr");
    sc_trace(mVcdFile, outStream_V_1_sel, "outStream_V_1_sel");
    sc_trace(mVcdFile, outStream_V_1_load_A, "outStream_V_1_load_A");
    sc_trace(mVcdFile, outStream_V_1_load_B, "outStream_V_1_load_B");
    sc_trace(mVcdFile, outStream_V_1_state, "outStream_V_1_state");
    sc_trace(mVcdFile, outStream_V_1_state_cmp_full, "outStream_V_1_state_cmp_full");
    sc_trace(mVcdFile, base_address, "base_address");
    sc_trace(mVcdFile, frame_buffer_dim, "frame_buffer_dim");
    sc_trace(mVcdFile, frame_buffer_offset, "frame_buffer_offset");
    sc_trace(mVcdFile, frame_buffer_number, "frame_buffer_number");
    sc_trace(mVcdFile, update_intr, "update_intr");
    sc_trace(mVcdFile, FRAME_OFFSET, "FRAME_OFFSET");
    sc_trace(mVcdFile, FRAME_BUFFER_NUMBER_r, "FRAME_BUFFER_NUMBER_r");
    sc_trace(mVcdFile, BASE_ADDRESS_r, "BASE_ADDRESS_r");
    sc_trace(mVcdFile, FRAME_BUFFER_DIM_r, "FRAME_BUFFER_DIM_r");
    sc_trace(mVcdFile, outStream_V_TDATA_blk_n, "outStream_V_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, tmp_9_reg_694, "tmp_9_reg_694");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter2, "ap_enable_reg_pp1_iter2");
    sc_trace(mVcdFile, tmp_9_reg_694_pp1_iter1_reg, "tmp_9_reg_694_pp1_iter1_reg");
    sc_trace(mVcdFile, base_ddr_addr_blk_n_AR, "base_ddr_addr_blk_n_AR");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_7_fu_425_p2, "tmp_7_fu_425_p2");
    sc_trace(mVcdFile, base_ddr_addr_blk_n_R, "base_ddr_addr_blk_n_R");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, exitcond_reg_680, "exitcond_reg_680");
    sc_trace(mVcdFile, base_ddr_addr_AWREADY, "base_ddr_addr_AWREADY");
    sc_trace(mVcdFile, base_ddr_addr_WREADY, "base_ddr_addr_WREADY");
    sc_trace(mVcdFile, base_ddr_addr_ARVALID, "base_ddr_addr_ARVALID");
    sc_trace(mVcdFile, base_ddr_addr_ARREADY, "base_ddr_addr_ARREADY");
    sc_trace(mVcdFile, base_ddr_addr_ARADDR, "base_ddr_addr_ARADDR");
    sc_trace(mVcdFile, base_ddr_addr_RVALID, "base_ddr_addr_RVALID");
    sc_trace(mVcdFile, base_ddr_addr_RREADY, "base_ddr_addr_RREADY");
    sc_trace(mVcdFile, base_ddr_addr_RDATA, "base_ddr_addr_RDATA");
    sc_trace(mVcdFile, base_ddr_addr_RLAST, "base_ddr_addr_RLAST");
    sc_trace(mVcdFile, base_ddr_addr_RID, "base_ddr_addr_RID");
    sc_trace(mVcdFile, base_ddr_addr_RUSER, "base_ddr_addr_RUSER");
    sc_trace(mVcdFile, base_ddr_addr_RRESP, "base_ddr_addr_RRESP");
    sc_trace(mVcdFile, base_ddr_addr_BVALID, "base_ddr_addr_BVALID");
    sc_trace(mVcdFile, base_ddr_addr_BRESP, "base_ddr_addr_BRESP");
    sc_trace(mVcdFile, base_ddr_addr_BID, "base_ddr_addr_BID");
    sc_trace(mVcdFile, base_ddr_addr_BUSER, "base_ddr_addr_BUSER");
    sc_trace(mVcdFile, indvar_reg_278, "indvar_reg_278");
    sc_trace(mVcdFile, indvar_reg_278_pp0_iter1_reg, "indvar_reg_278_pp0_iter1_reg");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter0, "ap_block_state10_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter1, "ap_block_state11_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter2, "ap_block_state12_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, j_reg_290, "j_reg_290");
    sc_trace(mVcdFile, tmp_1_fu_301_p1, "tmp_1_fu_301_p1");
    sc_trace(mVcdFile, tmp_5_fu_345_p1, "tmp_5_fu_345_p1");
    sc_trace(mVcdFile, update_intr_read_read_fu_154_p2, "update_intr_read_read_fu_154_p2");
    sc_trace(mVcdFile, tmp_4_fu_355_p2, "tmp_4_fu_355_p2");
    sc_trace(mVcdFile, tmp_4_reg_656, "tmp_4_reg_656");
    sc_trace(mVcdFile, offset_fu_401_p2, "offset_fu_401_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_1_fu_431_p2, "i_1_fu_431_p2");
    sc_trace(mVcdFile, i_1_reg_669, "i_1_reg_669");
    sc_trace(mVcdFile, ap_sig_ioackin_base_ddr_addr_ARREADY, "ap_sig_ioackin_base_ddr_addr_ARREADY");
    sc_trace(mVcdFile, ap_block_state3_io, "ap_block_state3_io");
    sc_trace(mVcdFile, exitcond_fu_448_p2, "exitcond_fu_448_p2");
    sc_trace(mVcdFile, exitcond_reg_680_pp0_iter1_reg, "exitcond_reg_680_pp0_iter1_reg");
    sc_trace(mVcdFile, indvar_next_fu_454_p2, "indvar_next_fu_454_p2");
    sc_trace(mVcdFile, indvar_next_reg_684, "indvar_next_reg_684");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, base_ddr_addr_addr_r_reg_689, "base_ddr_addr_addr_r_reg_689");
    sc_trace(mVcdFile, tmp_9_fu_465_p2, "tmp_9_fu_465_p2");
    sc_trace(mVcdFile, ap_block_state14_pp1_stage0_iter0, "ap_block_state14_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state15_pp1_stage0_iter1, "ap_block_state15_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state15_io, "ap_block_state15_io");
    sc_trace(mVcdFile, ap_block_state16_pp1_stage0_iter2, "ap_block_state16_pp1_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state16_io, "ap_block_state16_io");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, j_1_fu_471_p2, "j_1_fu_471_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, tmp_12_fu_477_p1, "tmp_12_fu_477_p1");
    sc_trace(mVcdFile, tmp_12_reg_703, "tmp_12_reg_703");
    sc_trace(mVcdFile, tmp_29_fu_607_p1, "tmp_29_fu_607_p1");
    sc_trace(mVcdFile, offset_1_fu_612_p2, "offset_1_fu_612_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state10, "ap_condition_pp0_exit_iter0_state10");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state14, "ap_condition_pp1_exit_iter0_state14");
    sc_trace(mVcdFile, buffer_address0, "buffer_address0");
    sc_trace(mVcdFile, buffer_ce0, "buffer_ce0");
    sc_trace(mVcdFile, buffer_q0, "buffer_q0");
    sc_trace(mVcdFile, buffer_address1, "buffer_address1");
    sc_trace(mVcdFile, buffer_ce1, "buffer_ce1");
    sc_trace(mVcdFile, buffer_we1, "buffer_we1");
    sc_trace(mVcdFile, i_op_assign_reg_230, "i_op_assign_reg_230");
    sc_trace(mVcdFile, i_op_assign_1_reg_239, "i_op_assign_1_reg_239");
    sc_trace(mVcdFile, tmp_3_reg_248, "tmp_3_reg_248");
    sc_trace(mVcdFile, offset1_reg_257, "offset1_reg_257");
    sc_trace(mVcdFile, i_reg_267, "i_reg_267");
    sc_trace(mVcdFile, ap_phi_mux_indvar_phi_fu_282_p4, "ap_phi_mux_indvar_phi_fu_282_p4");
    sc_trace(mVcdFile, indvar1_fu_460_p1, "indvar1_fu_460_p1");
    sc_trace(mVcdFile, gepindex2_cast_fu_491_p1, "gepindex2_cast_fu_491_p1");
    sc_trace(mVcdFile, tmp_8_fu_437_p1, "tmp_8_fu_437_p1");
    sc_trace(mVcdFile, ap_reg_ioackin_base_ddr_addr_ARREADY, "ap_reg_ioackin_base_ddr_addr_ARREADY");
    sc_trace(mVcdFile, ap_block_pp1_stage0_01001, "ap_block_pp1_stage0_01001");
    sc_trace(mVcdFile, tmp_2_fu_335_p4, "tmp_2_fu_335_p4");
    sc_trace(mVcdFile, tmp_fu_361_p1, "tmp_fu_361_p1");
    sc_trace(mVcdFile, t_V_fu_365_p3, "t_V_fu_365_p3");
    sc_trace(mVcdFile, inner_index_V_1_fu_371_p2, "inner_index_V_1_fu_371_p2");
    sc_trace(mVcdFile, r_V_fu_385_p0, "r_V_fu_385_p0");
    sc_trace(mVcdFile, r_V_fu_385_p1, "r_V_fu_385_p1");
    sc_trace(mVcdFile, r_V_fu_385_p2, "r_V_fu_385_p2");
    sc_trace(mVcdFile, tmp_s_fu_391_p4, "tmp_s_fu_391_p4");
    sc_trace(mVcdFile, tmp_6_fu_411_p4, "tmp_6_fu_411_p4");
    sc_trace(mVcdFile, tmp_10_fu_421_p1, "tmp_10_fu_421_p1");
    sc_trace(mVcdFile, gepindex_cast_fu_481_p4, "gepindex_cast_fu_481_p4");
    sc_trace(mVcdFile, start_pos_fu_496_p3, "start_pos_fu_496_p3");
    sc_trace(mVcdFile, end_pos_fu_503_p2, "end_pos_fu_503_p2");
    sc_trace(mVcdFile, tmp_14_fu_515_p1, "tmp_14_fu_515_p1");
    sc_trace(mVcdFile, tmp_15_fu_519_p1, "tmp_15_fu_519_p1");
    sc_trace(mVcdFile, tmp_13_fu_509_p2, "tmp_13_fu_509_p2");
    sc_trace(mVcdFile, tmp_17_fu_533_p2, "tmp_17_fu_533_p2");
    sc_trace(mVcdFile, tmp_19_fu_545_p2, "tmp_19_fu_545_p2");
    sc_trace(mVcdFile, tmp_16_fu_523_p4, "tmp_16_fu_523_p4");
    sc_trace(mVcdFile, tmp_18_fu_539_p2, "tmp_18_fu_539_p2");
    sc_trace(mVcdFile, tmp_20_fu_551_p3, "tmp_20_fu_551_p3");
    sc_trace(mVcdFile, tmp_22_fu_567_p3, "tmp_22_fu_567_p3");
    sc_trace(mVcdFile, tmp_23_fu_575_p2, "tmp_23_fu_575_p2");
    sc_trace(mVcdFile, tmp_21_fu_559_p3, "tmp_21_fu_559_p3");
    sc_trace(mVcdFile, tmp_24_fu_581_p1, "tmp_24_fu_581_p1");
    sc_trace(mVcdFile, tmp_25_fu_585_p1, "tmp_25_fu_585_p1");
    sc_trace(mVcdFile, tmp_26_fu_589_p2, "tmp_26_fu_589_p2");
    sc_trace(mVcdFile, tmp_27_fu_595_p2, "tmp_27_fu_595_p2");
    sc_trace(mVcdFile, tmp_28_fu_601_p2, "tmp_28_fu_601_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
    sc_trace(mVcdFile, r_V_fu_385_p00, "r_V_fu_385_p00");
    sc_trace(mVcdFile, r_V_fu_385_p10, "r_V_fu_385_p10");
#endif

    }
    mHdltvinHandle.open("ddr_to_axis_reader.hdltvin.dat");
    mHdltvoutHandle.open("ddr_to_axis_reader.hdltvout.dat");
}

ddr_to_axis_reader::~ddr_to_axis_reader() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete ddr_to_axis_reader_AXILiteS_s_axi_U;
    delete ddr_to_axis_reader_base_ddr_addr_m_axi_U;
    delete buffer_U;
}

void ddr_to_axis_reader::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void ddr_to_axis_reader::thread_ap_var_for_const6() {
    ap_var_for_const6 = ap_const_logic_0;
}

void ddr_to_axis_reader::thread_ap_var_for_const7() {
    ap_var_for_const7 = ap_const_lv32_0;
}

void ddr_to_axis_reader::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv1_0;
}

void ddr_to_axis_reader::thread_ap_var_for_const4() {
    ap_var_for_const4 = ap_const_lv2_0;
}

void ddr_to_axis_reader::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv32_200;
}

void ddr_to_axis_reader::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv3_0;
}

void ddr_to_axis_reader::thread_ap_var_for_const5() {
    ap_var_for_const5 = ap_const_lv4_0;
}

void ddr_to_axis_reader::thread_ap_var_for_const9() {
    ap_var_for_const9 = ap_const_lv8_0;
}

void ddr_to_axis_reader::thread_ap_var_for_const8() {
    ap_var_for_const8 = ap_const_lv64_0;
}

void ddr_to_axis_reader::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state10.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state10.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state10.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp1_stage0_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state14.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp1_stage0_subdone.read())) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state14.read())) {
                ap_enable_reg_pp1_iter1 = (ap_condition_pp1_exit_iter0_state14.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
            }
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp1_stage0_subdone.read())) {
            ap_enable_reg_pp1_iter2 = ap_enable_reg_pp1_iter1.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
            ap_enable_reg_pp1_iter2 = ap_const_logic_0;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ioackin_base_ddr_addr_ARREADY = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(tmp_7_fu_425_p2.read(), ap_const_lv1_1))) {
            if (!(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()) || esl_seteq<1,1,1>(outStream_V_1_ack_in.read(), ap_const_logic_0))) {
                ap_reg_ioackin_base_ddr_addr_ARREADY = ap_const_logic_0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, base_ddr_addr_ARREADY.read()) && 
                        esl_seteq<1,1,1>(outStream_V_1_ack_in.read(), ap_const_logic_1))) {
                ap_reg_ioackin_base_ddr_addr_ARREADY = ap_const_logic_1;
            }
        }
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, update_intr_read_read_fu_154_p2.read())) {
            i_op_assign_1_reg_239 = BASE_ADDRESS_r.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, update_intr_read_read_fu_154_p2.read())) {
            i_op_assign_1_reg_239 = tmp_5_fu_345_p1.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, update_intr_read_read_fu_154_p2.read())) {
            i_op_assign_reg_230 = FRAME_OFFSET.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, update_intr_read_read_fu_154_p2.read())) {
            i_op_assign_reg_230 = frame_buffer_offset.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        i_reg_267 = i_1_reg_669.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_267 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_680.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        indvar_reg_278 = indvar_next_reg_684.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        indvar_reg_278 = ap_const_lv10_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        j_reg_290 = ap_const_lv13_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_fu_465_p2.read()))) {
        j_reg_290 = j_1_fu_471_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        offset1_reg_257 = offset_1_fu_612_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        offset1_reg_257 = offset_fu_401_p2.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        outStream_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, outStream_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, outStream_V_1_vld_out.read()))) {
            outStream_V_1_sel_rd =  (sc_logic) (~outStream_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        outStream_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, outStream_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, outStream_V_1_ack_in.read()))) {
            outStream_V_1_sel_wr =  (sc_logic) (~outStream_V_1_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        outStream_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, outStream_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, outStream_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(outStream_V_1_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, outStream_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(outStream_V_1_state.read(), ap_const_lv2_2)))) {
            outStream_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, outStream_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, outStream_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(outStream_V_1_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, outStream_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(outStream_V_1_state.read(), ap_const_lv2_1)))) {
            outStream_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, outStream_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(outStream_V_1_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, outStream_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(outStream_V_1_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(outStream_V_1_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, outStream_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, outStream_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, outStream_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, outStream_V_1_ack_out.read()))))) {
            outStream_V_1_state = ap_const_lv2_3;
        } else {
            outStream_V_1_state = ap_const_lv2_2;
        }
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, update_intr_read_read_fu_154_p2.read())) {
            tmp_3_reg_248 = FRAME_BUFFER_NUMBER_r.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, update_intr_read_read_fu_154_p2.read())) {
            tmp_3_reg_248 = tmp_1_fu_301_p1.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_1, update_intr_read_read_fu_154_p2.read()))) {
        BASE_ADDRESS_r = tmp_5_fu_345_p1.read();
        FRAME_BUFFER_DIM_r = frame_buffer_dim.read();
        FRAME_BUFFER_NUMBER_r = tmp_1_fu_301_p1.read();
        FRAME_OFFSET = frame_buffer_offset.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_680.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        base_ddr_addr_addr_r_reg_689 = base_ddr_addr_RDATA.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_reg_680 = exitcond_fu_448_p2.read();
        exitcond_reg_680_pp0_iter1_reg = exitcond_reg_680.read();
        indvar_reg_278_pp0_iter1_reg = indvar_reg_278.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && !(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()) || esl_seteq<1,1,1>(outStream_V_1_ack_in.read(), ap_const_logic_0)))) {
        i_1_reg_669 = i_1_fu_431_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1))) {
        indvar_next_reg_684 = indvar_next_fu_454_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, outStream_V_1_load_A.read())) {
        outStream_V_1_payload_A = tmp_29_fu_607_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, outStream_V_1_load_B.read())) {
        outStream_V_1_payload_B = tmp_29_fu_607_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_fu_465_p2.read()))) {
        tmp_12_reg_703 = tmp_12_fu_477_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        tmp_4_reg_656 = tmp_4_fu_355_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_9_reg_694 = tmp_9_fu_465_p2.read();
        tmp_9_reg_694_pp1_iter1_reg = tmp_9_reg_694.read();
    }
}

void ddr_to_axis_reader::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[9];
}

void ddr_to_axis_reader::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[11];
}

void ddr_to_axis_reader::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void ddr_to_axis_reader::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[10];
}

void ddr_to_axis_reader::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[12];
}

void ddr_to_axis_reader::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void ddr_to_axis_reader::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void ddr_to_axis_reader::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void ddr_to_axis_reader::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ddr_to_axis_reader::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_680.read()) && esl_seteq<1,1,1>(ap_const_logic_0, base_ddr_addr_RVALID.read()));
}

void ddr_to_axis_reader::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_680.read()) && esl_seteq<1,1,1>(ap_const_logic_0, base_ddr_addr_RVALID.read()));
}

void ddr_to_axis_reader::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ddr_to_axis_reader::thread_ap_block_pp1_stage0_01001() {
    ap_block_pp1_stage0_01001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ddr_to_axis_reader::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state15_io.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp1_iter2.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state16_io.read())));
}

void ddr_to_axis_reader::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state15_io.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp1_iter2.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state16_io.read())));
}

void ddr_to_axis_reader::thread_ap_block_state10_pp0_stage0_iter0() {
    ap_block_state10_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ddr_to_axis_reader::thread_ap_block_state11_pp0_stage0_iter1() {
    ap_block_state11_pp0_stage0_iter1 = (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_680.read()) && esl_seteq<1,1,1>(ap_const_logic_0, base_ddr_addr_RVALID.read()));
}

void ddr_to_axis_reader::thread_ap_block_state12_pp0_stage0_iter2() {
    ap_block_state12_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ddr_to_axis_reader::thread_ap_block_state14_pp1_stage0_iter0() {
    ap_block_state14_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ddr_to_axis_reader::thread_ap_block_state15_io() {
    ap_block_state15_io = (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_reg_694.read()) && esl_seteq<1,1,1>(outStream_V_1_ack_in.read(), ap_const_logic_0));
}

void ddr_to_axis_reader::thread_ap_block_state15_pp1_stage0_iter1() {
    ap_block_state15_pp1_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ddr_to_axis_reader::thread_ap_block_state16_io() {
    ap_block_state16_io = (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_reg_694_pp1_iter1_reg.read()) && esl_seteq<1,1,1>(outStream_V_1_ack_in.read(), ap_const_logic_0));
}

void ddr_to_axis_reader::thread_ap_block_state16_pp1_stage0_iter2() {
    ap_block_state16_pp1_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ddr_to_axis_reader::thread_ap_block_state3_io() {
    ap_block_state3_io = (esl_seteq<1,1,1>(tmp_7_fu_425_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_base_ddr_addr_ARREADY.read()));
}

void ddr_to_axis_reader::thread_ap_condition_pp0_exit_iter0_state10() {
    if (esl_seteq<1,1,1>(exitcond_fu_448_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state10 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state10 = ap_const_logic_0;
    }
}

void ddr_to_axis_reader::thread_ap_condition_pp1_exit_iter0_state14() {
    if (esl_seteq<1,1,1>(tmp_9_fu_465_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp1_exit_iter0_state14 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state14 = ap_const_logic_0;
    }
}

void ddr_to_axis_reader::thread_ap_done() {
    if ((!(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()) || esl_seteq<1,1,1>(outStream_V_1_ack_in.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(tmp_7_fu_425_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void ddr_to_axis_reader::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void ddr_to_axis_reader::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void ddr_to_axis_reader::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void ddr_to_axis_reader::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void ddr_to_axis_reader::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter2.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void ddr_to_axis_reader::thread_ap_phi_mux_indvar_phi_fu_282_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_680.read()))) {
        ap_phi_mux_indvar_phi_fu_282_p4 = indvar_next_reg_684.read();
    } else {
        ap_phi_mux_indvar_phi_fu_282_p4 = indvar_reg_278.read();
    }
}

void ddr_to_axis_reader::thread_ap_ready() {
    if ((!(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()) || esl_seteq<1,1,1>(outStream_V_1_ack_in.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(tmp_7_fu_425_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void ddr_to_axis_reader::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void ddr_to_axis_reader::thread_ap_sig_ioackin_base_ddr_addr_ARREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_base_ddr_addr_ARREADY.read())) {
        ap_sig_ioackin_base_ddr_addr_ARREADY = base_ddr_addr_ARREADY.read();
    } else {
        ap_sig_ioackin_base_ddr_addr_ARREADY = ap_const_logic_1;
    }
}

void ddr_to_axis_reader::thread_base_ddr_addr_ARADDR() {
    base_ddr_addr_ARADDR =  (sc_lv<32>) (tmp_8_fu_437_p1.read());
}

void ddr_to_axis_reader::thread_base_ddr_addr_ARVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(tmp_7_fu_425_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(outStream_V_1_ack_in.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_base_ddr_addr_ARREADY.read()))) {
        base_ddr_addr_ARVALID = ap_const_logic_1;
    } else {
        base_ddr_addr_ARVALID = ap_const_logic_0;
    }
}

void ddr_to_axis_reader::thread_base_ddr_addr_RREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_680.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        base_ddr_addr_RREADY = ap_const_logic_1;
    } else {
        base_ddr_addr_RREADY = ap_const_logic_0;
    }
}

void ddr_to_axis_reader::thread_base_ddr_addr_blk_n_AR() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(tmp_7_fu_425_p2.read(), ap_const_lv1_1))) {
        base_ddr_addr_blk_n_AR = m_axi_base_ddr_addr_ARREADY.read();
    } else {
        base_ddr_addr_blk_n_AR = ap_const_logic_1;
    }
}

void ddr_to_axis_reader::thread_base_ddr_addr_blk_n_R() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_680.read()))) {
        base_ddr_addr_blk_n_R = m_axi_base_ddr_addr_RVALID.read();
    } else {
        base_ddr_addr_blk_n_R = ap_const_logic_1;
    }
}

void ddr_to_axis_reader::thread_buffer_address0() {
    buffer_address0 =  (sc_lv<9>) (gepindex2_cast_fu_491_p1.read());
}

void ddr_to_axis_reader::thread_buffer_address1() {
    buffer_address1 =  (sc_lv<9>) (indvar1_fu_460_p1.read());
}

void ddr_to_axis_reader::thread_buffer_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_1))) {
        buffer_ce0 = ap_const_logic_1;
    } else {
        buffer_ce0 = ap_const_logic_0;
    }
}

void ddr_to_axis_reader::thread_buffer_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1))) {
        buffer_ce1 = ap_const_logic_1;
    } else {
        buffer_ce1 = ap_const_logic_0;
    }
}

void ddr_to_axis_reader::thread_buffer_we1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_680_pp0_iter1_reg.read()))) {
        buffer_we1 = ap_const_logic_1;
    } else {
        buffer_we1 = ap_const_logic_0;
    }
}

void ddr_to_axis_reader::thread_end_pos_fu_503_p2() {
    end_pos_fu_503_p2 = (start_pos_fu_496_p3.read() | ap_const_lv6_7);
}

void ddr_to_axis_reader::thread_exitcond_fu_448_p2() {
    exitcond_fu_448_p2 = (!ap_phi_mux_indvar_phi_fu_282_p4.read().is_01() || !ap_const_lv10_200.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_phi_fu_282_p4.read() == ap_const_lv10_200);
}

void ddr_to_axis_reader::thread_gepindex2_cast_fu_491_p1() {
    gepindex2_cast_fu_491_p1 = esl_zext<64,9>(gepindex_cast_fu_481_p4.read());
}

void ddr_to_axis_reader::thread_gepindex_cast_fu_481_p4() {
    gepindex_cast_fu_481_p4 = j_reg_290.read().range(11, 3);
}

void ddr_to_axis_reader::thread_i_1_fu_431_p2() {
    i_1_fu_431_p2 = (!i_reg_267.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(i_reg_267.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void ddr_to_axis_reader::thread_indvar1_fu_460_p1() {
    indvar1_fu_460_p1 = esl_zext<64,10>(indvar_reg_278_pp0_iter1_reg.read());
}

void ddr_to_axis_reader::thread_indvar_next_fu_454_p2() {
    indvar_next_fu_454_p2 = (!ap_phi_mux_indvar_phi_fu_282_p4.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(ap_phi_mux_indvar_phi_fu_282_p4.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void ddr_to_axis_reader::thread_inner_index_V_1_fu_371_p2() {
    inner_index_V_1_fu_371_p2 = (!ap_const_lv8_FF.is_01() || !t_V_fu_365_p3.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_FF) + sc_biguint<8>(t_V_fu_365_p3.read()));
}

void ddr_to_axis_reader::thread_j_1_fu_471_p2() {
    j_1_fu_471_p2 = (!j_reg_290.read().is_01() || !ap_const_lv13_1.is_01())? sc_lv<13>(): (sc_biguint<13>(j_reg_290.read()) + sc_biguint<13>(ap_const_lv13_1));
}

void ddr_to_axis_reader::thread_offset_1_fu_612_p2() {
    offset_1_fu_612_p2 = (!offset1_reg_257.read().is_01() || !ap_const_lv32_200.is_01())? sc_lv<32>(): (sc_bigint<32>(offset1_reg_257.read()) + sc_biguint<32>(ap_const_lv32_200));
}

void ddr_to_axis_reader::thread_offset_fu_401_p2() {
    offset_fu_401_p2 = (!i_op_assign_1_reg_239.read().is_01() || !tmp_s_fu_391_p4.read().is_01())? sc_lv<32>(): (sc_biguint<32>(i_op_assign_1_reg_239.read()) + sc_biguint<32>(tmp_s_fu_391_p4.read()));
}

void ddr_to_axis_reader::thread_outStream_V_1_ack_in() {
    outStream_V_1_ack_in = outStream_V_1_state.read()[1];
}

void ddr_to_axis_reader::thread_outStream_V_1_ack_out() {
    outStream_V_1_ack_out = outStream_V_TREADY.read();
}

void ddr_to_axis_reader::thread_outStream_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, outStream_V_1_sel.read())) {
        outStream_V_1_data_out = outStream_V_1_payload_B.read();
    } else {
        outStream_V_1_data_out = outStream_V_1_payload_A.read();
    }
}

void ddr_to_axis_reader::thread_outStream_V_1_load_A() {
    outStream_V_1_load_A = (outStream_V_1_state_cmp_full.read() & ~outStream_V_1_sel_wr.read());
}

void ddr_to_axis_reader::thread_outStream_V_1_load_B() {
    outStream_V_1_load_B = (outStream_V_1_sel_wr.read() & outStream_V_1_state_cmp_full.read());
}

void ddr_to_axis_reader::thread_outStream_V_1_sel() {
    outStream_V_1_sel = outStream_V_1_sel_rd.read();
}

void ddr_to_axis_reader::thread_outStream_V_1_state_cmp_full() {
    outStream_V_1_state_cmp_full =  (sc_logic) ((!outStream_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(outStream_V_1_state.read() != ap_const_lv2_1))[0];
}

void ddr_to_axis_reader::thread_outStream_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_reg_694.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        outStream_V_1_vld_in = ap_const_logic_1;
    } else {
        outStream_V_1_vld_in = ap_const_logic_0;
    }
}

void ddr_to_axis_reader::thread_outStream_V_1_vld_out() {
    outStream_V_1_vld_out = outStream_V_1_state.read()[0];
}

void ddr_to_axis_reader::thread_outStream_V_TDATA() {
    outStream_V_TDATA = outStream_V_1_data_out.read();
}

void ddr_to_axis_reader::thread_outStream_V_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_reg_694.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_enable_reg_pp1_iter2.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_reg_694_pp1_iter1_reg.read())))) {
        outStream_V_TDATA_blk_n = outStream_V_1_state.read()[1];
    } else {
        outStream_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void ddr_to_axis_reader::thread_outStream_V_TVALID() {
    outStream_V_TVALID = outStream_V_1_state.read()[0];
}

void ddr_to_axis_reader::thread_r_V_fu_385_p0() {
    r_V_fu_385_p0 =  (sc_lv<8>) (r_V_fu_385_p00.read());
}

void ddr_to_axis_reader::thread_r_V_fu_385_p00() {
    r_V_fu_385_p00 = esl_zext<35,8>(inner_index_V_1_fu_371_p2.read());
}

void ddr_to_axis_reader::thread_r_V_fu_385_p1() {
    r_V_fu_385_p1 =  (sc_lv<32>) (r_V_fu_385_p10.read());
}

void ddr_to_axis_reader::thread_r_V_fu_385_p10() {
    r_V_fu_385_p10 = esl_zext<35,32>(i_op_assign_reg_230.read());
}

void ddr_to_axis_reader::thread_r_V_fu_385_p2() {
    r_V_fu_385_p2 = (!r_V_fu_385_p0.read().is_01() || !r_V_fu_385_p1.read().is_01())? sc_lv<35>(): sc_biguint<8>(r_V_fu_385_p0.read()) * sc_biguint<32>(r_V_fu_385_p1.read());
}

void ddr_to_axis_reader::thread_start_pos_fu_496_p3() {
    start_pos_fu_496_p3 = esl_concat<3,3>(tmp_12_reg_703.read(), ap_const_lv3_0);
}

void ddr_to_axis_reader::thread_t_V_fu_365_p3() {
    t_V_fu_365_p3 = (!tmp_4_reg_656.read()[0].is_01())? sc_lv<8>(): ((tmp_4_reg_656.read()[0].to_bool())? tmp_fu_361_p1.read(): frame_index_V.read());
}

void ddr_to_axis_reader::thread_tmp_10_fu_421_p1() {
    tmp_10_fu_421_p1 = esl_zext<32,20>(tmp_6_fu_411_p4.read());
}

void ddr_to_axis_reader::thread_tmp_12_fu_477_p1() {
    tmp_12_fu_477_p1 = j_reg_290.read().range(3-1, 0);
}

void ddr_to_axis_reader::thread_tmp_13_fu_509_p2() {
    tmp_13_fu_509_p2 = (!start_pos_fu_496_p3.read().is_01() || !end_pos_fu_503_p2.read().is_01())? sc_lv<1>(): (sc_biguint<6>(start_pos_fu_496_p3.read()) > sc_biguint<6>(end_pos_fu_503_p2.read()));
}

void ddr_to_axis_reader::thread_tmp_14_fu_515_p1() {
    tmp_14_fu_515_p1 = esl_zext<7,6>(start_pos_fu_496_p3.read());
}

void ddr_to_axis_reader::thread_tmp_15_fu_519_p1() {
    tmp_15_fu_519_p1 = esl_zext<7,6>(end_pos_fu_503_p2.read());
}

void ddr_to_axis_reader::thread_tmp_16_fu_523_p4() {
    tmp_16_fu_523_p4 = buffer_q0.read().range(0, 63);
}

void ddr_to_axis_reader::thread_tmp_17_fu_533_p2() {
    tmp_17_fu_533_p2 = (!tmp_14_fu_515_p1.read().is_01() || !tmp_15_fu_519_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_14_fu_515_p1.read()) - sc_biguint<7>(tmp_15_fu_519_p1.read()));
}

void ddr_to_axis_reader::thread_tmp_18_fu_539_p2() {
    tmp_18_fu_539_p2 = (tmp_14_fu_515_p1.read() ^ ap_const_lv7_3F);
}

void ddr_to_axis_reader::thread_tmp_19_fu_545_p2() {
    tmp_19_fu_545_p2 = (!tmp_15_fu_519_p1.read().is_01() || !tmp_14_fu_515_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_15_fu_519_p1.read()) - sc_biguint<7>(tmp_14_fu_515_p1.read()));
}

void ddr_to_axis_reader::thread_tmp_1_fu_301_p1() {
    tmp_1_fu_301_p1 = esl_zext<32,8>(frame_buffer_number.read());
}

void ddr_to_axis_reader::thread_tmp_20_fu_551_p3() {
    tmp_20_fu_551_p3 = (!tmp_13_fu_509_p2.read()[0].is_01())? sc_lv<7>(): ((tmp_13_fu_509_p2.read()[0].to_bool())? tmp_17_fu_533_p2.read(): tmp_19_fu_545_p2.read());
}

void ddr_to_axis_reader::thread_tmp_21_fu_559_p3() {
    tmp_21_fu_559_p3 = (!tmp_13_fu_509_p2.read()[0].is_01())? sc_lv<64>(): ((tmp_13_fu_509_p2.read()[0].to_bool())? tmp_16_fu_523_p4.read(): buffer_q0.read());
}

void ddr_to_axis_reader::thread_tmp_22_fu_567_p3() {
    tmp_22_fu_567_p3 = (!tmp_13_fu_509_p2.read()[0].is_01())? sc_lv<7>(): ((tmp_13_fu_509_p2.read()[0].to_bool())? tmp_18_fu_539_p2.read(): tmp_14_fu_515_p1.read());
}

void ddr_to_axis_reader::thread_tmp_23_fu_575_p2() {
    tmp_23_fu_575_p2 = (!ap_const_lv7_3F.is_01() || !tmp_20_fu_551_p3.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_3F) - sc_biguint<7>(tmp_20_fu_551_p3.read()));
}

void ddr_to_axis_reader::thread_tmp_24_fu_581_p1() {
    tmp_24_fu_581_p1 = esl_zext<64,7>(tmp_22_fu_567_p3.read());
}

void ddr_to_axis_reader::thread_tmp_25_fu_585_p1() {
    tmp_25_fu_585_p1 = esl_zext<64,7>(tmp_23_fu_575_p2.read());
}

void ddr_to_axis_reader::thread_tmp_26_fu_589_p2() {
    tmp_26_fu_589_p2 = (!tmp_24_fu_581_p1.read().is_01())? sc_lv<64>(): tmp_21_fu_559_p3.read() >> (unsigned short)tmp_24_fu_581_p1.read().to_uint();
}

void ddr_to_axis_reader::thread_tmp_27_fu_595_p2() {
    tmp_27_fu_595_p2 = (!tmp_25_fu_585_p1.read().is_01())? sc_lv<64>(): ap_const_lv64_FFFFFFFFFFFFFFFF >> (unsigned short)tmp_25_fu_585_p1.read().to_uint();
}

void ddr_to_axis_reader::thread_tmp_28_fu_601_p2() {
    tmp_28_fu_601_p2 = (tmp_26_fu_589_p2.read() & tmp_27_fu_595_p2.read());
}

void ddr_to_axis_reader::thread_tmp_29_fu_607_p1() {
    tmp_29_fu_607_p1 = tmp_28_fu_601_p2.read().range(8-1, 0);
}

void ddr_to_axis_reader::thread_tmp_2_fu_335_p4() {
    tmp_2_fu_335_p4 = base_address.read().range(31, 3);
}

void ddr_to_axis_reader::thread_tmp_4_fu_355_p2() {
    tmp_4_fu_355_p2 = (!frame_index_V.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(frame_index_V.read() == ap_const_lv8_0);
}

void ddr_to_axis_reader::thread_tmp_5_fu_345_p1() {
    tmp_5_fu_345_p1 = esl_zext<32,29>(tmp_2_fu_335_p4.read());
}

void ddr_to_axis_reader::thread_tmp_6_fu_411_p4() {
    tmp_6_fu_411_p4 = FRAME_BUFFER_DIM_r.read().range(31, 12);
}

void ddr_to_axis_reader::thread_tmp_7_fu_425_p2() {
    tmp_7_fu_425_p2 = (!i_reg_267.read().is_01() || !tmp_10_fu_421_p1.read().is_01())? sc_lv<1>(): (sc_biguint<32>(i_reg_267.read()) < sc_biguint<32>(tmp_10_fu_421_p1.read()));
}

void ddr_to_axis_reader::thread_tmp_8_fu_437_p1() {
    tmp_8_fu_437_p1 = esl_sext<64,32>(offset1_reg_257.read());
}

void ddr_to_axis_reader::thread_tmp_9_fu_465_p2() {
    tmp_9_fu_465_p2 = (!j_reg_290.read().is_01() || !ap_const_lv13_1000.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_290.read() == ap_const_lv13_1000);
}

void ddr_to_axis_reader::thread_tmp_fu_361_p1() {
    tmp_fu_361_p1 = tmp_3_reg_248.read().range(8-1, 0);
}

void ddr_to_axis_reader::thread_tmp_s_fu_391_p4() {
    tmp_s_fu_391_p4 = r_V_fu_385_p2.read().range(34, 3);
}

void ddr_to_axis_reader::thread_update_intr_read_read_fu_154_p2() {
    update_intr_read_read_fu_154_p2 =  (sc_lv<1>) (update_intr.read());
}

void ddr_to_axis_reader::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()) || esl_seteq<1,1,1>(outStream_V_1_ack_in.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(tmp_7_fu_425_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((!(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()) || esl_seteq<1,1,1>(outStream_V_1_ack_in.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(tmp_7_fu_425_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 512 : 
            if ((!(esl_seteq<1,1,1>(exitcond_fu_448_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1)) && !(esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1)) || (esl_seteq<1,1,1>(exitcond_fu_448_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            break;
        case 2048 : 
            if ((!(esl_seteq<1,1,1>(tmp_9_fu_465_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp1_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp1_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter2.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp1_stage0_subdone.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp1_iter2.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(tmp_9_fu_465_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp1_stage0_subdone.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state17;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXX";
            break;
    }
}

void ddr_to_axis_reader::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"outStream_V_TDATA\" :  \"" << outStream_V_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outStream_V_TVALID\" :  \"" << outStream_V_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"outStream_V_TREADY\" :  \"" << outStream_V_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_AWVALID\" :  \"" << m_axi_base_ddr_addr_AWVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_base_ddr_addr_AWREADY\" :  \"" << m_axi_base_ddr_addr_AWREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_AWADDR\" :  \"" << m_axi_base_ddr_addr_AWADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_AWID\" :  \"" << m_axi_base_ddr_addr_AWID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_AWLEN\" :  \"" << m_axi_base_ddr_addr_AWLEN.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_AWSIZE\" :  \"" << m_axi_base_ddr_addr_AWSIZE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_AWBURST\" :  \"" << m_axi_base_ddr_addr_AWBURST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_AWLOCK\" :  \"" << m_axi_base_ddr_addr_AWLOCK.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_AWCACHE\" :  \"" << m_axi_base_ddr_addr_AWCACHE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_AWPROT\" :  \"" << m_axi_base_ddr_addr_AWPROT.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_AWQOS\" :  \"" << m_axi_base_ddr_addr_AWQOS.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_AWREGION\" :  \"" << m_axi_base_ddr_addr_AWREGION.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_AWUSER\" :  \"" << m_axi_base_ddr_addr_AWUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_WVALID\" :  \"" << m_axi_base_ddr_addr_WVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_base_ddr_addr_WREADY\" :  \"" << m_axi_base_ddr_addr_WREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_WDATA\" :  \"" << m_axi_base_ddr_addr_WDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_WSTRB\" :  \"" << m_axi_base_ddr_addr_WSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_WLAST\" :  \"" << m_axi_base_ddr_addr_WLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_WID\" :  \"" << m_axi_base_ddr_addr_WID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_WUSER\" :  \"" << m_axi_base_ddr_addr_WUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_ARVALID\" :  \"" << m_axi_base_ddr_addr_ARVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_base_ddr_addr_ARREADY\" :  \"" << m_axi_base_ddr_addr_ARREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_ARADDR\" :  \"" << m_axi_base_ddr_addr_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_ARID\" :  \"" << m_axi_base_ddr_addr_ARID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_ARLEN\" :  \"" << m_axi_base_ddr_addr_ARLEN.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_ARSIZE\" :  \"" << m_axi_base_ddr_addr_ARSIZE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_ARBURST\" :  \"" << m_axi_base_ddr_addr_ARBURST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_ARLOCK\" :  \"" << m_axi_base_ddr_addr_ARLOCK.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_ARCACHE\" :  \"" << m_axi_base_ddr_addr_ARCACHE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_ARPROT\" :  \"" << m_axi_base_ddr_addr_ARPROT.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_ARQOS\" :  \"" << m_axi_base_ddr_addr_ARQOS.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_ARREGION\" :  \"" << m_axi_base_ddr_addr_ARREGION.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_ARUSER\" :  \"" << m_axi_base_ddr_addr_ARUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_base_ddr_addr_RVALID\" :  \"" << m_axi_base_ddr_addr_RVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_RREADY\" :  \"" << m_axi_base_ddr_addr_RREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_base_ddr_addr_RDATA\" :  \"" << m_axi_base_ddr_addr_RDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_base_ddr_addr_RLAST\" :  \"" << m_axi_base_ddr_addr_RLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_base_ddr_addr_RID\" :  \"" << m_axi_base_ddr_addr_RID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_base_ddr_addr_RUSER\" :  \"" << m_axi_base_ddr_addr_RUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_base_ddr_addr_RRESP\" :  \"" << m_axi_base_ddr_addr_RRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_base_ddr_addr_BVALID\" :  \"" << m_axi_base_ddr_addr_BVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_base_ddr_addr_BREADY\" :  \"" << m_axi_base_ddr_addr_BREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_base_ddr_addr_BRESP\" :  \"" << m_axi_base_ddr_addr_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_base_ddr_addr_BID\" :  \"" << m_axi_base_ddr_addr_BID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_base_ddr_addr_BUSER\" :  \"" << m_axi_base_ddr_addr_BUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"frame_index_V\" :  \"" << frame_index_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

