// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XOV7670_MEMCPY_H
#define XOV7670_MEMCPY_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xov7670_memcpy_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XOv7670_memcpy_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XOv7670_memcpy;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XOv7670_memcpy_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XOv7670_memcpy_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XOv7670_memcpy_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XOv7670_memcpy_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XOv7670_memcpy_Initialize(XOv7670_memcpy *InstancePtr, u16 DeviceId);
XOv7670_memcpy_Config* XOv7670_memcpy_LookupConfig(u16 DeviceId);
int XOv7670_memcpy_CfgInitialize(XOv7670_memcpy *InstancePtr, XOv7670_memcpy_Config *ConfigPtr);
#else
int XOv7670_memcpy_Initialize(XOv7670_memcpy *InstancePtr, const char* InstanceName);
int XOv7670_memcpy_Release(XOv7670_memcpy *InstancePtr);
#endif

void XOv7670_memcpy_Start(XOv7670_memcpy *InstancePtr);
u32 XOv7670_memcpy_IsDone(XOv7670_memcpy *InstancePtr);
u32 XOv7670_memcpy_IsIdle(XOv7670_memcpy *InstancePtr);
u32 XOv7670_memcpy_IsReady(XOv7670_memcpy *InstancePtr);
void XOv7670_memcpy_EnableAutoRestart(XOv7670_memcpy *InstancePtr);
void XOv7670_memcpy_DisableAutoRestart(XOv7670_memcpy *InstancePtr);

void XOv7670_memcpy_Set_data_out(XOv7670_memcpy *InstancePtr, u32 Data);
u32 XOv7670_memcpy_Get_data_out(XOv7670_memcpy *InstancePtr);

void XOv7670_memcpy_InterruptGlobalEnable(XOv7670_memcpy *InstancePtr);
void XOv7670_memcpy_InterruptGlobalDisable(XOv7670_memcpy *InstancePtr);
void XOv7670_memcpy_InterruptEnable(XOv7670_memcpy *InstancePtr, u32 Mask);
void XOv7670_memcpy_InterruptDisable(XOv7670_memcpy *InstancePtr, u32 Mask);
void XOv7670_memcpy_InterruptClear(XOv7670_memcpy *InstancePtr, u32 Mask);
u32 XOv7670_memcpy_InterruptGetEnabled(XOv7670_memcpy *InstancePtr);
u32 XOv7670_memcpy_InterruptGetStatus(XOv7670_memcpy *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
