-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.1
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity axi_stream_to_vga is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    selftest : IN STD_LOGIC;
    inStream_V_V_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    inStream_V_V_TVALID : IN STD_LOGIC;
    inStream_V_V_TREADY : OUT STD_LOGIC;
    R_V : OUT STD_LOGIC_VECTOR (3 downto 0);
    G_V : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_V : OUT STD_LOGIC_VECTOR (3 downto 0);
    V_SYNC_V : OUT STD_LOGIC_VECTOR (0 downto 0);
    H_SYNC_V : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of axi_stream_to_vga is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "axi_stream_to_vga,hls_ip_2018_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.146750,HLS_SYN_LAT=1260002,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=136,HLS_SYN_LUT=574}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv21_3 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000011";
    constant ap_const_lv21_2 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000010";
    constant ap_const_lv21_1 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000001";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv10_22 : STD_LOGIC_VECTOR (9 downto 0) := "0000100010";
    constant ap_const_lv10_203 : STD_LOGIC_VECTOR (9 downto 0) := "1000000011";
    constant ap_const_lv19_668A0 : STD_LOGIC_VECTOR (18 downto 0) := "1100110100010100000";
    constant ap_const_lv19_1 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000001";
    constant ap_const_lv10_320 : STD_LOGIC_VECTOR (9 downto 0) := "1100100000";
    constant ap_const_lv10_3DE : STD_LOGIC_VECTOR (9 downto 0) := "1111011110";
    constant ap_const_lv10_3DD : STD_LOGIC_VECTOR (9 downto 0) := "1111011101";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv11_770 : STD_LOGIC_VECTOR (10 downto 0) := "11101110000";
    constant ap_const_lv10_8F : STD_LOGIC_VECTOR (9 downto 0) := "0010001111";
    constant ap_const_lv10_310 : STD_LOGIC_VECTOR (9 downto 0) := "1100010000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv10_5F : STD_LOGIC_VECTOR (9 downto 0) := "0001011111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal color_blinking_V : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal inStream_V_V_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal exitcond_flatten_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond2_fu_447_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal selftest_read_read_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal exitcond_flatten_reg_568 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond2_reg_588 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal indvar_flatten_reg_192 : STD_LOGIC_VECTOR (18 downto 0);
    signal y_reg_203 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_reg_214 : STD_LOGIC_VECTOR (9 downto 0);
    signal op2_V_read_assign_fu_262_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal op2_V_read_assign_reg_554 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_i_fu_274_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_i_reg_563 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_predicate_op71_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal indvar_flatten_next_fu_320_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal indvar_flatten_next_reg_572 : STD_LOGIC_VECTOR (18 downto 0);
    signal x_mid2_fu_332_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_mid2_reg_577 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_mid2_fu_411_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_mid2_reg_583 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_1_fu_509_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_1_reg_595 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_predicate_op101_read_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_phi_mux_indvar_flatten_phi_fu_196_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_phi_mux_y_phi_fu_207_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_mux_x_phi_fu_218_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal R_temp_V_read_assign_fu_122 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_i_fu_483_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal G_temp_V_read_assign_fu_126 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_predicate_op96_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal B_temp_V_read_assign_fu_130 : STD_LOGIC_VECTOR (3 downto 0);
    signal not_mid2_fu_376_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal V_SYNC_V_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal not_1_fu_498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal H_SYNC_V_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_block_pp0_stage2_01001 : BOOLEAN;
    signal R_V_preg : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal G_V_preg : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal B_V_preg : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal tmp_4_fu_280_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_fu_296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_coordinate_V_mid2_s_fu_340_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_s_fu_354_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_8_fu_360_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp1_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_mid1_fu_385_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_mid1_fu_391_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp2_mid1_fu_397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp2_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_cast_fu_419_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_6_fu_429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_435_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp2_mid2_fu_403_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_441_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_coordinate_V_mid2_fu_348_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_Val2_s_fu_423_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_10_fu_471_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_i_fu_479_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_9_fu_463_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_251 : BOOLEAN;


begin




    B_V_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                B_V_preg <= ap_const_lv4_0;
            else
                if ((ap_const_boolean_1 = ap_condition_251)) then
                    if ((or_cond2_reg_588 = ap_const_lv1_1)) then 
                        B_V_preg <= B_temp_V_read_assign_fu_130;
                    elsif ((or_cond2_reg_588 = ap_const_lv1_0)) then 
                        B_V_preg <= ap_const_lv4_0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    G_V_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                G_V_preg <= ap_const_lv4_0;
            else
                if ((ap_const_boolean_1 = ap_condition_251)) then
                    if ((or_cond2_reg_588 = ap_const_lv1_1)) then 
                        G_V_preg <= G_temp_V_read_assign_fu_126;
                    elsif ((or_cond2_reg_588 = ap_const_lv1_0)) then 
                        G_V_preg <= ap_const_lv4_0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    H_SYNC_V_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                H_SYNC_V_preg <= ap_const_lv1_0;
            else
                if ((((or_cond2_reg_588 = ap_const_lv1_0) and (exitcond_flatten_reg_568 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((or_cond2_reg_588 = ap_const_lv1_1) and (exitcond_flatten_reg_568 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then 
                    H_SYNC_V_preg <= not_1_fu_498_p2;
                end if; 
            end if;
        end if;
    end process;


    R_V_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                R_V_preg <= ap_const_lv4_0;
            else
                if ((ap_const_boolean_1 = ap_condition_251)) then
                    if ((or_cond2_reg_588 = ap_const_lv1_1)) then 
                        R_V_preg <= R_temp_V_read_assign_fu_122;
                    elsif ((or_cond2_reg_588 = ap_const_lv1_0)) then 
                        R_V_preg <= ap_const_lv4_0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    V_SYNC_V_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                V_SYNC_V_preg <= ap_const_lv1_0;
            else
                if ((((or_cond2_fu_447_p2 = ap_const_lv1_1) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((or_cond2_fu_447_p2 = ap_const_lv1_0) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                    V_SYNC_V_preg <= not_mid2_fu_376_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    color_blinking_V_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                color_blinking_V <= ap_const_lv4_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    color_blinking_V <= op2_V_read_assign_fu_262_p2;
                end if; 
            end if;
        end if;
    end process;


    B_temp_V_read_assign_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_op101_read_state4 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                B_temp_V_read_assign_fu_130 <= inStream_V_V_TDATA(7 downto 4);
            elsif ((((selftest_read_read_fu_134_p2 = ap_const_lv1_1) and (or_cond2_fu_447_p2 = ap_const_lv1_1) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_2_i_fu_483_p4 = ap_const_lv21_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((selftest_read_read_fu_134_p2 = ap_const_lv1_1) and (or_cond2_fu_447_p2 = ap_const_lv1_1) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_2_i_fu_483_p4 = ap_const_lv21_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                B_temp_V_read_assign_fu_130 <= tmp_6_i_reg_563;
            elsif ((((or_cond2_fu_447_p2 = ap_const_lv1_1) and (tmp_reg_559 = ap_const_lv1_0) and (selftest_read_read_fu_134_p2 = ap_const_lv1_0) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((selftest_read_read_fu_134_p2 = ap_const_lv1_1) and (or_cond2_fu_447_p2 = ap_const_lv1_1) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_2_i_fu_483_p4 = ap_const_lv21_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((selftest_read_read_fu_134_p2 = ap_const_lv1_1) and (or_cond2_fu_447_p2 = ap_const_lv1_1) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_2_i_fu_483_p4 = ap_const_lv21_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                B_temp_V_read_assign_fu_130 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    G_temp_V_read_assign_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_op96_read_state3 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                G_temp_V_read_assign_fu_126 <= inStream_V_V_TDATA(7 downto 4);
            elsif ((((or_cond2_fu_447_p2 = ap_const_lv1_1) and (tmp_reg_559 = ap_const_lv1_0) and (selftest_read_read_fu_134_p2 = ap_const_lv1_0) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((selftest_read_read_fu_134_p2 = ap_const_lv1_1) and (or_cond2_fu_447_p2 = ap_const_lv1_1) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_2_i_fu_483_p4 = ap_const_lv21_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((selftest_read_read_fu_134_p2 = ap_const_lv1_1) and (or_cond2_fu_447_p2 = ap_const_lv1_1) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_2_i_fu_483_p4 = ap_const_lv21_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((selftest_read_read_fu_134_p2 = ap_const_lv1_1) and (or_cond2_fu_447_p2 = ap_const_lv1_1) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_2_i_fu_483_p4 = ap_const_lv21_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((selftest_read_read_fu_134_p2 = ap_const_lv1_1) and (or_cond2_fu_447_p2 = ap_const_lv1_1) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_2_i_fu_483_p4 = ap_const_lv21_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                G_temp_V_read_assign_fu_126 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    R_temp_V_read_assign_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((selftest_read_read_fu_134_p2 = ap_const_lv1_1) and (or_cond2_fu_447_p2 = ap_const_lv1_1) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_2_i_fu_483_p4 = ap_const_lv21_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((selftest_read_read_fu_134_p2 = ap_const_lv1_1) and (or_cond2_fu_447_p2 = ap_const_lv1_1) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_2_i_fu_483_p4 = ap_const_lv21_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                R_temp_V_read_assign_fu_122 <= ap_const_lv4_0;
            elsif ((((selftest_read_read_fu_134_p2 = ap_const_lv1_1) and (or_cond2_fu_447_p2 = ap_const_lv1_1) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_2_i_fu_483_p4 = ap_const_lv21_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((selftest_read_read_fu_134_p2 = ap_const_lv1_1) and (or_cond2_fu_447_p2 = ap_const_lv1_1) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_2_i_fu_483_p4 = ap_const_lv21_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                R_temp_V_read_assign_fu_122 <= op2_V_read_assign_reg_554;
            elsif (((ap_predicate_op71_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                R_temp_V_read_assign_fu_122 <= inStream_V_V_TDATA(7 downto 4);
            elsif (((or_cond2_fu_447_p2 = ap_const_lv1_1) and (tmp_reg_559 = ap_const_lv1_0) and (selftest_read_read_fu_134_p2 = ap_const_lv1_0) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                R_temp_V_read_assign_fu_122 <= ap_const_lv4_F;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_reg_568 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten_reg_192 <= indvar_flatten_next_reg_572;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvar_flatten_reg_192 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    x_reg_214_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_reg_568 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                x_reg_214 <= x_1_reg_595;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                x_reg_214 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;

    y_reg_203_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_reg_568 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                y_reg_203 <= y_mid2_reg_583;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                y_reg_203 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                exitcond_flatten_reg_568 <= exitcond_flatten_fu_314_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                indvar_flatten_next_reg_572 <= indvar_flatten_next_fu_320_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                op2_V_read_assign_reg_554 <= op2_V_read_assign_fu_262_p2;
                tmp_6_i_reg_563 <= tmp_6_i_fu_274_p2;
                tmp_reg_559 <= (0=>inStream_V_V_TVALID, others=>'-');
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                or_cond2_reg_588 <= or_cond2_fu_447_p2;
                x_mid2_reg_577 <= x_mid2_fu_332_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_reg_568 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then
                x_1_reg_595 <= x_1_fu_509_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                y_mid2_reg_583 <= y_mid2_fu_411_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter0, exitcond_flatten_fu_314_p2, ap_block_pp0_stage0_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage1_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((exitcond_flatten_fu_314_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((exitcond_flatten_fu_314_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;

    B_V_assign_proc : process(or_cond2_reg_588, B_temp_V_read_assign_fu_130, B_V_preg, ap_condition_251)
    begin
        if ((ap_const_boolean_1 = ap_condition_251)) then
            if ((or_cond2_reg_588 = ap_const_lv1_1)) then 
                B_V <= B_temp_V_read_assign_fu_130;
            elsif ((or_cond2_reg_588 = ap_const_lv1_0)) then 
                B_V <= ap_const_lv4_0;
            else 
                B_V <= B_V_preg;
            end if;
        else 
            B_V <= B_V_preg;
        end if; 
    end process;


    G_V_assign_proc : process(or_cond2_reg_588, G_temp_V_read_assign_fu_126, G_V_preg, ap_condition_251)
    begin
        if ((ap_const_boolean_1 = ap_condition_251)) then
            if ((or_cond2_reg_588 = ap_const_lv1_1)) then 
                G_V <= G_temp_V_read_assign_fu_126;
            elsif ((or_cond2_reg_588 = ap_const_lv1_0)) then 
                G_V <= ap_const_lv4_0;
            else 
                G_V <= G_V_preg;
            end if;
        else 
            G_V <= G_V_preg;
        end if; 
    end process;


    H_SYNC_V_assign_proc : process(ap_enable_reg_pp0_iter0, exitcond_flatten_reg_568, or_cond2_reg_588, ap_CS_fsm_pp0_stage2, not_1_fu_498_p2, H_SYNC_V_preg, ap_block_pp0_stage2_01001)
    begin
        if ((((or_cond2_reg_588 = ap_const_lv1_0) and (exitcond_flatten_reg_568 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((or_cond2_reg_588 = ap_const_lv1_1) and (exitcond_flatten_reg_568 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then 
            H_SYNC_V <= not_1_fu_498_p2;
        else 
            H_SYNC_V <= H_SYNC_V_preg;
        end if; 
    end process;


    R_V_assign_proc : process(or_cond2_reg_588, R_temp_V_read_assign_fu_122, R_V_preg, ap_condition_251)
    begin
        if ((ap_const_boolean_1 = ap_condition_251)) then
            if ((or_cond2_reg_588 = ap_const_lv1_1)) then 
                R_V <= R_temp_V_read_assign_fu_122;
            elsif ((or_cond2_reg_588 = ap_const_lv1_0)) then 
                R_V <= ap_const_lv4_0;
            else 
                R_V <= R_V_preg;
            end if;
        else 
            R_V <= R_V_preg;
        end if; 
    end process;


    V_SYNC_V_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, exitcond_flatten_fu_314_p2, or_cond2_fu_447_p2, not_mid2_fu_376_p3, V_SYNC_V_preg, ap_block_pp0_stage0_01001)
    begin
        if ((((or_cond2_fu_447_p2 = ap_const_lv1_1) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((or_cond2_fu_447_p2 = ap_const_lv1_0) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            V_SYNC_V <= not_mid2_fu_376_p3;
        else 
            V_SYNC_V <= V_SYNC_V_preg;
        end if; 
    end process;

    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state6 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(inStream_V_V_TVALID, ap_enable_reg_pp0_iter0, ap_predicate_op71_read_state2)
    begin
                ap_block_pp0_stage0_01001 <= ((inStream_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(inStream_V_V_TVALID, ap_enable_reg_pp0_iter0, ap_predicate_op71_read_state2)
    begin
                ap_block_pp0_stage0_11001 <= ((inStream_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(inStream_V_V_TVALID, ap_enable_reg_pp0_iter0, ap_predicate_op71_read_state2)
    begin
                ap_block_pp0_stage0_subdone <= ((inStream_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(inStream_V_V_TVALID, ap_enable_reg_pp0_iter0, ap_predicate_op96_read_state3)
    begin
                ap_block_pp0_stage1_11001 <= ((inStream_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op96_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(inStream_V_V_TVALID, ap_enable_reg_pp0_iter0, ap_predicate_op96_read_state3)
    begin
                ap_block_pp0_stage1_subdone <= ((inStream_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op96_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_01001_assign_proc : process(inStream_V_V_TVALID, ap_enable_reg_pp0_iter0, ap_predicate_op101_read_state4)
    begin
                ap_block_pp0_stage2_01001 <= ((inStream_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op101_read_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage2_11001_assign_proc : process(inStream_V_V_TVALID, ap_enable_reg_pp0_iter0, ap_predicate_op101_read_state4)
    begin
                ap_block_pp0_stage2_11001 <= ((inStream_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op101_read_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage2_subdone_assign_proc : process(inStream_V_V_TVALID, ap_enable_reg_pp0_iter0, ap_predicate_op101_read_state4)
    begin
                ap_block_pp0_stage2_subdone <= ((inStream_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op101_read_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_state2_pp0_stage0_iter0_assign_proc : process(inStream_V_V_TVALID, ap_predicate_op71_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter0 <= ((inStream_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1));
    end process;


    ap_block_state3_pp0_stage1_iter0_assign_proc : process(inStream_V_V_TVALID, ap_predicate_op96_read_state3)
    begin
                ap_block_state3_pp0_stage1_iter0 <= ((inStream_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op96_read_state3 = ap_const_boolean_1));
    end process;


    ap_block_state4_pp0_stage2_iter0_assign_proc : process(inStream_V_V_TVALID, ap_predicate_op101_read_state4)
    begin
                ap_block_state4_pp0_stage2_iter0 <= ((inStream_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op101_read_state4 = ap_const_boolean_1));
    end process;

        ap_block_state5_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_251_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_01001)
    begin
                ap_condition_251 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(exitcond_flatten_fu_314_p2)
    begin
        if ((exitcond_flatten_fu_314_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_indvar_flatten_phi_fu_196_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, exitcond_flatten_reg_568, indvar_flatten_reg_192, indvar_flatten_next_reg_572, ap_enable_reg_pp0_iter1)
    begin
        if (((exitcond_flatten_reg_568 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_indvar_flatten_phi_fu_196_p4 <= indvar_flatten_next_reg_572;
        else 
            ap_phi_mux_indvar_flatten_phi_fu_196_p4 <= indvar_flatten_reg_192;
        end if; 
    end process;


    ap_phi_mux_x_phi_fu_218_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, exitcond_flatten_reg_568, x_reg_214, x_1_reg_595, ap_enable_reg_pp0_iter1)
    begin
        if (((exitcond_flatten_reg_568 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_x_phi_fu_218_p4 <= x_1_reg_595;
        else 
            ap_phi_mux_x_phi_fu_218_p4 <= x_reg_214;
        end if; 
    end process;


    ap_phi_mux_y_phi_fu_207_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, exitcond_flatten_reg_568, y_reg_203, y_mid2_reg_583, ap_enable_reg_pp0_iter1)
    begin
        if (((exitcond_flatten_reg_568 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_y_phi_fu_207_p4 <= y_mid2_reg_583;
        else 
            ap_phi_mux_y_phi_fu_207_p4 <= y_reg_203;
        end if; 
    end process;


    ap_predicate_op101_read_state4_assign_proc : process(selftest_read_read_fu_134_p2, tmp_reg_559, exitcond_flatten_reg_568, or_cond2_reg_588)
    begin
                ap_predicate_op101_read_state4 <= ((or_cond2_reg_588 = ap_const_lv1_1) and (tmp_reg_559 = ap_const_lv1_1) and (exitcond_flatten_reg_568 = ap_const_lv1_0) and (selftest_read_read_fu_134_p2 = ap_const_lv1_0));
    end process;


    ap_predicate_op71_read_state2_assign_proc : process(exitcond_flatten_fu_314_p2, or_cond2_fu_447_p2, selftest_read_read_fu_134_p2, tmp_reg_559)
    begin
                ap_predicate_op71_read_state2 <= ((tmp_reg_559 = ap_const_lv1_1) and (or_cond2_fu_447_p2 = ap_const_lv1_1) and (selftest_read_read_fu_134_p2 = ap_const_lv1_0) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0));
    end process;


    ap_predicate_op96_read_state3_assign_proc : process(selftest_read_read_fu_134_p2, tmp_reg_559, exitcond_flatten_reg_568, or_cond2_reg_588)
    begin
                ap_predicate_op96_read_state3 <= ((or_cond2_reg_588 = ap_const_lv1_1) and (tmp_reg_559 = ap_const_lv1_1) and (exitcond_flatten_reg_568 = ap_const_lv1_0) and (selftest_read_read_fu_134_p2 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    exitcond_flatten_fu_314_p2 <= "1" when (ap_phi_mux_indvar_flatten_phi_fu_196_p4 = ap_const_lv19_668A0) else "0";
    icmp1_fu_370_p2 <= "0" when (tmp_8_fu_360_p4 = ap_const_lv9_0) else "1";
    icmp_fu_290_p2 <= "0" when (tmp_4_fu_280_p4 = ap_const_lv9_0) else "1";

    inStream_V_V_TDATA_blk_n_assign_proc : process(inStream_V_V_TVALID, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, exitcond_flatten_fu_314_p2, or_cond2_fu_447_p2, selftest_read_read_fu_134_p2, tmp_reg_559, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, exitcond_flatten_reg_568, or_cond2_reg_588, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2) and (or_cond2_reg_588 = ap_const_lv1_1) and (tmp_reg_559 = ap_const_lv1_1) and (exitcond_flatten_reg_568 = ap_const_lv1_0) and (selftest_read_read_fu_134_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (or_cond2_reg_588 = ap_const_lv1_1) and (tmp_reg_559 = ap_const_lv1_1) and (exitcond_flatten_reg_568 = ap_const_lv1_0) and (selftest_read_read_fu_134_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((tmp_reg_559 = ap_const_lv1_1) and (or_cond2_fu_447_p2 = ap_const_lv1_1) and (selftest_read_read_fu_134_p2 = ap_const_lv1_0) and (exitcond_flatten_fu_314_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            inStream_V_V_TDATA_blk_n <= inStream_V_V_TVALID;
        else 
            inStream_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    inStream_V_V_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_predicate_op71_read_state2, ap_block_pp0_stage0_11001, ap_predicate_op101_read_state4, ap_block_pp0_stage2_11001, ap_predicate_op96_read_state3, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_predicate_op101_read_state4 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001)) or ((ap_predicate_op96_read_state3 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_predicate_op71_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inStream_V_V_TREADY <= ap_const_logic_1;
        else 
            inStream_V_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    indvar_flatten_next_fu_320_p2 <= std_logic_vector(unsigned(ap_phi_mux_indvar_flatten_phi_fu_196_p4) + unsigned(ap_const_lv19_1));
    not_1_fu_498_p2 <= "1" when (unsigned(x_mid2_reg_577) > unsigned(ap_const_lv10_5F)) else "0";
    not_mid2_fu_376_p3 <= 
        icmp1_fu_370_p2 when (tmp_5_fu_326_p2(0) = '1') else 
        icmp_fu_290_p2;
    op2_V_read_assign_fu_262_p2 <= std_logic_vector(unsigned(color_blinking_V) + unsigned(ap_const_lv4_1));
    or_cond2_fu_447_p2 <= (tmp2_mid2_fu_403_p3 and tmp1_fu_441_p2);
    p_Val2_s_fu_423_p2 <= std_logic_vector(unsigned(tmp_5_cast_fu_419_p1) + unsigned(ap_const_lv11_770));
    selftest_read_read_fu_134_p2 <= (0=>selftest, others=>'-');
    tmp1_fu_441_p2 <= (tmp_7_fu_435_p2 and tmp_6_fu_429_p2);
    tmp2_fu_308_p2 <= (tmp_3_fu_302_p2 and tmp_2_fu_296_p2);
    tmp2_mid1_fu_397_p2 <= (tmp_3_mid1_fu_391_p2 and tmp_2_mid1_fu_385_p2);
    tmp2_mid2_fu_403_p3 <= 
        tmp2_mid1_fu_397_p2 when (tmp_5_fu_326_p2(0) = '1') else 
        tmp2_fu_308_p2;
    tmp_10_fu_471_p3 <= p_Val2_s_fu_423_p2(5 downto 5);
    tmp_1_i_fu_479_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_471_p3),19));
    tmp_2_fu_296_p2 <= "1" when (unsigned(ap_phi_mux_y_phi_fu_207_p4) > unsigned(ap_const_lv10_22)) else "0";
    tmp_2_i_fu_483_p4 <= ((ap_const_lv1_0 & tmp_1_i_fu_479_p1) & tmp_9_fu_463_p3);
    tmp_2_mid1_fu_385_p2 <= "1" when (unsigned(y_s_fu_354_p2) > unsigned(ap_const_lv10_22)) else "0";
    tmp_3_fu_302_p2 <= "1" when (unsigned(ap_phi_mux_y_phi_fu_207_p4) < unsigned(ap_const_lv10_203)) else "0";
    tmp_3_mid1_fu_391_p2 <= "1" when (unsigned(y_s_fu_354_p2) < unsigned(ap_const_lv10_203)) else "0";
    tmp_4_fu_280_p4 <= ap_phi_mux_y_phi_fu_207_p4(9 downto 1);
    tmp_5_cast_fu_419_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_mid2_fu_332_p3),11));
    tmp_5_fu_326_p2 <= "1" when (ap_phi_mux_x_phi_fu_218_p4 = ap_const_lv10_320) else "0";
    tmp_6_fu_429_p2 <= "1" when (unsigned(x_mid2_fu_332_p3) > unsigned(ap_const_lv10_8F)) else "0";
    tmp_6_i_fu_274_p2 <= std_logic_vector(signed(ap_const_lv4_E) - signed(color_blinking_V));
    tmp_7_fu_435_p2 <= "1" when (unsigned(x_mid2_fu_332_p3) < unsigned(ap_const_lv10_310)) else "0";
    tmp_8_fu_360_p4 <= y_s_fu_354_p2(9 downto 1);
    tmp_9_fu_463_p3 <= y_coordinate_V_mid2_fu_348_p2(5 downto 5);
    x_1_fu_509_p2 <= std_logic_vector(unsigned(x_mid2_reg_577) + unsigned(ap_const_lv10_1));
    x_mid2_fu_332_p3 <= 
        ap_const_lv10_0 when (tmp_5_fu_326_p2(0) = '1') else 
        ap_phi_mux_x_phi_fu_218_p4;
    y_coordinate_V_mid2_fu_348_p2 <= std_logic_vector(unsigned(ap_phi_mux_y_phi_fu_207_p4) + unsigned(y_coordinate_V_mid2_s_fu_340_p3));
    y_coordinate_V_mid2_s_fu_340_p3 <= 
        ap_const_lv10_3DE when (tmp_5_fu_326_p2(0) = '1') else 
        ap_const_lv10_3DD;
    y_mid2_fu_411_p3 <= 
        y_s_fu_354_p2 when (tmp_5_fu_326_p2(0) = '1') else 
        ap_phi_mux_y_phi_fu_207_p4;
    y_s_fu_354_p2 <= std_logic_vector(unsigned(ap_phi_mux_y_phi_fu_207_p4) + unsigned(ap_const_lv10_1));
end behav;
