# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/design_1/ip/design_1_mux_sd_ov_1_0/design_1_mux_sd_ov_1_0.xci
# IP: The module: 'design_1_mux_sd_ov_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/design_1/ip/design_1_mux_sd_ov_1_0/constraints/mux_sd_ov_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mux_sd_ov_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/design_1/ip/design_1_mux_sd_ov_1_0/design_1_mux_sd_ov_1_0.xci
# IP: The module: 'design_1_mux_sd_ov_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.srcs/sources_1/bd/design_1/ip/design_1_mux_sd_ov_1_0/constraints/mux_sd_ov_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mux_sd_ov_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
