webtalk_init -webtalk_dir /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-07-10 18:48:01" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4c3059fnhrhtfkja6256qu8hh0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.1_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3169.382 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8,247 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1594394896000" -context "sdk\\\\application/1594394896000"
webtalk_add_data -client sdk -key hwid -value "1593989423000" -context "sdk\\\\application/1594394896000"
webtalk_add_data -client sdk -key bspid -value "1593989493000" -context "sdk\\\\application/1594394896000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1594394896000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1594394896000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1594394896000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1594394896000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1594394896000"
webtalk_add_data -client sdk -key Procused -value "psu_cortexa53" -context "sdk\\\\application/1594394896000"
webtalk_add_data -client sdk -key projSize -value "245.9375" -context "sdk\\\\application/1594394896000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1594399681600"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1594399681600"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1594399681600"
webtalk_add_data -client sdk -key DebugCount -value "9" -context "sdk\\\\bsp/1594399681600"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1594399681600"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1594399681600"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1594399681600"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1594399681600"
webtalk_transmit -clientid 854787473 -regid "" -xml /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.sdk/webtalk/usage_statistics_ext_sdk.xml -html /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /media/kidre/Dati/GIT_TEST/bare-metalProva/myproj/project_1.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
